-- ============================================
-- DATABASE UPDATES: 100 FAQs CHO CHATBOT
-- ============================================

-- Chọn database
USE `vinhlong_hotel`;

-- Đảm bảo bảng faqs tồn tại
CREATE TABLE IF NOT EXISTS `faqs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(500) NOT NULL COMMENT 'Câu hỏi',
  `answer` TEXT NOT NULL COMMENT 'Câu trả lời',
  `keywords` TEXT COMMENT 'Từ khóa để tìm kiếm (phân cách bằng dấu phẩy)',
  `category` VARCHAR(100) DEFAULT 'general' COMMENT 'Danh mục: general, booking, payment, room, etc',
  `priority` INT(11) DEFAULT 0 COMMENT 'Độ ưu tiên (số càng cao càng ưu tiên)',
  `active` TINYINT(1) DEFAULT 1 COMMENT '1=hiển thị, 0=ẩn',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_category` (`category`),
  KEY `idx_active` (`active`),
  KEY `idx_priority` (`priority`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Xóa dữ liệu cũ nếu muốn (uncomment để xóa)
-- DELETE FROM `faqs`;

-- ============================================
-- INSERT 100 FAQs (INSERT IGNORE để tránh duplicate)
-- ============================================

INSERT IGNORE INTO `faqs` (`question`, `answer`, `keywords`, `category`, `priority`) VALUES

-- ========== CHUNG / GIỚI THIỆU (10 câu) ==========
('Xin chào', 'Xin chào! Tôi là trợ lý ảo của Vĩnh Long Hotel. Tôi có thể giúp bạn về: đặt phòng, giá cả, tiện ích, địa điểm du lịch, hoặc thanh toán. Bạn muốn biết thông tin gì?', 'xin chào, hello, hi, chào, chào bạn', 'general', 10),
('Giờ làm việc', 'Vĩnh Long Hotel hoạt động 24/7. Bạn có thể đặt phòng và liên hệ với chúng tôi bất cứ lúc nào. Phòng tiếp tân luôn có nhân viên sẵn sàng hỗ trợ bạn.', 'giờ làm việc, giờ mở cửa, hoạt động, thời gian', 'general', 9),
('Địa chỉ khách sạn', 'Vĩnh Long Hotel tọa lạc tại trung tâm thành phố Vĩnh Long, thuận tiện cho việc di chuyển đến các điểm du lịch nổi tiếng. Bạn có thể xem địa chỉ chi tiết trên trang "Liên hệ" hoặc sử dụng Google Maps.', 'địa chỉ, địa điểm, vị trí, ở đâu, location, address', 'general', 8),
('Liên hệ', 'Bạn có thể liên hệ với chúng tôi qua:\n- Hotline: Xem trên trang "Liên hệ"\n- Email: Xem trên trang "Liên hệ"\n- Chat trực tuyến: Sử dụng cửa sổ chat này\n- Trực tiếp tại khách sạn', 'liên hệ, contact, hotline, số điện thoại, email', 'general', 8),
('Về Vĩnh Long Hotel', 'Vĩnh Long Hotel là khách sạn nghỉ dưỡng sang trọng tại trung tâm Vĩnh Long, mang đến trải nghiệm tuyệt vời với dịch vụ chuyên nghiệp, tiện ích hiện đại và giá cả hợp lý.', 'về chúng tôi, giới thiệu, about, hotel', 'general', 7),
('Chính sách bảo mật', 'Chúng tôi cam kết bảo mật thông tin cá nhân của khách hàng. Mọi thông tin đều được mã hóa và chỉ sử dụng cho mục đích phục vụ đặt phòng và dịch vụ.', 'bảo mật, privacy, chính sách, thông tin', 'general', 6),
('Đánh giá khách sạn', 'Vĩnh Long Hotel nhận được nhiều đánh giá tích cực từ khách hàng về chất lượng phòng, dịch vụ và giá cả. Bạn có thể xem các đánh giá trên trang "Đánh giá" hoặc các nền tảng đặt phòng trực tuyến.', 'đánh giá, review, rating, sao, feedback', 'general', 6),
('Thành viên', 'Khi đăng ký tài khoản, bạn tự động trở thành thành viên:\n- Silver: Thành viên mới\n- Gold: Đã đặt phòng 3 lần\n- Platinum: Đã đặt phòng 10 lần\n\nMỗi hạng có ưu đãi riêng!', 'thành viên, member, membership, hạng, tier', 'general', 7),
('Ưu đãi đặc biệt', 'Chúng tôi thường xuyên có các chương trình khuyến mãi:\n- Giảm giá theo mùa\n- Combo đặc biệt\n- Ưu đãi cho thành viên\n- Mã giảm giá\n\nBạn có thể xem các ưu đãi hiện có trên trang chủ!', 'ưu đãi, khuyến mãi, promotion, discount, giảm giá', 'general', 7),
('Tại sao chọn Vĩnh Long Hotel', 'Vĩnh Long Hotel mang đến:\n✅ Vị trí đắc địa, thuận tiện\n✅ Phòng nghỉ sang trọng, tiện nghi\n✅ Dịch vụ chuyên nghiệp 24/7\n✅ Giá cả hợp lý\n✅ Nhiều ưu đãi hấp dẫn\n✅ Hỗ trợ đặt phòng dễ dàng', 'tại sao, why, lý do, ưu điểm, điểm mạnh', 'general', 6),

-- ========== ĐẶT PHÒNG (20 câu) ==========
('Làm sao để đặt phòng?', 'Để đặt phòng, bạn có thể:\n1. Vào trang "Phòng" và chọn phòng yêu thích\n2. Chọn ngày check-in và check-out\n3. Nhấn "Đặt ngay" và điền thông tin\n4. Thanh toán qua QR Code\n\nHoặc bạn có thể nói "Đặt phòng" để tôi hỗ trợ trực tiếp!', 'đặt phòng, booking, book, reserve, đặt, cách đặt', 'booking', 10),
('Check-in và check-out', 'Thời gian check-in: Từ 14:00\nThời gian check-out: Trước 12:00\n\nBạn có thể yêu cầu check-in sớm hoặc check-out muộn (có thể phụ thu). Vui lòng liên hệ trước với chúng tôi.', 'check-in, check-out, nhận phòng, trả phòng, thời gian', 'booking', 9),
('Có thể đặt phòng qua điện thoại không?', 'Có! Bạn có thể đặt phòng qua:\n- Hotline: Xem trên trang "Liên hệ"\n- Chat trực tuyến: Sử dụng cửa sổ chat này\n- Website: Trang "Phòng"\n\nChúng tôi hỗ trợ 24/7!', 'đặt qua điện thoại, hotline, phone, gọi điện', 'booking', 8),
('Cần thông tin gì để đặt phòng?', 'Để đặt phòng, bạn cần cung cấp:\n- Họ tên\n- Số điện thoại\n- Email\n- Ngày check-in và check-out\n- Số lượng khách (người lớn, trẻ em)\n- Phương thức thanh toán', 'thông tin, cần gì, yêu cầu, điều kiện', 'booking', 8),
('Có thể đặt phòng cho người khác không?', 'Có! Bạn có thể đặt phòng cho người khác. Khi đặt, vui lòng cung cấp thông tin của người sẽ nhận phòng. Người nhận phòng cần mang theo CMND/CCCD khi check-in.', 'đặt cho người khác, người thân, bạn bè', 'booking', 7),
('Đặt phòng có cần đặt cọc không?', 'Tùy theo loại phòng và thời gian đặt, có thể yêu cầu đặt cọc. Thông thường:\n- Phòng thường: Không cần đặt cọc\n- Phòng VIP: Có thể yêu cầu đặt cọc\n\nChi tiết sẽ được thông báo khi đặt phòng.', 'đặt cọc, deposit, cọc, tiền cọc', 'booking', 7),
('Có thể thay đổi ngày đặt phòng không?', 'Có! Bạn có thể thay đổi ngày đặt phòng:\n- Miễn phí nếu thay đổi trước 24h\n- Có thể phụ thu nếu thay đổi trong vòng 24h\n\nVui lòng liên hệ với chúng tôi để được hỗ trợ.', 'thay đổi ngày, đổi ngày, change date, modify', 'booking', 7),
('Có thể hủy đặt phòng không?', 'Có! Bạn có thể hủy đặt phòng:\n- Hủy miễn phí nếu hủy trước 24h\n- Vào trang "Lịch sử đặt phòng" để hủy\n- Hoặc liên hệ trực tiếp với chúng tôi\n\nChúng tôi luôn hỗ trợ bạn tốt nhất!', 'hủy, cancel, hủy đặt, hủy phòng, hủy booking', 'booking', 9),
('Chính sách hủy phòng', 'Chính sách hủy phòng:\n✅ Hủy miễn phí: Trước 24h\n⚠️ Hủy có phí: Trong vòng 24h (tùy loại phòng)\n❌ Không hoàn tiền: Sau thời gian check-in\n\nChi tiết sẽ được thông báo khi đặt phòng.', 'chính sách hủy, cancellation policy, quy định hủy', 'booking', 8),
('Có thể đặt nhiều phòng không?', 'Có! Bạn có thể đặt nhiều phòng cùng lúc. Vui lòng:\n1. Chọn số lượng phòng khi đặt\n2. Hoặc đặt từng phòng riêng\n3. Hoặc liên hệ trực tiếp để được hỗ trợ tốt nhất', 'nhiều phòng, multiple rooms, đặt nhiều', 'booking', 6),
('Đặt phòng có cần CMND không?', 'Khi đặt phòng online, bạn không cần CMND. Tuy nhiên, khi check-in, người nhận phòng cần mang theo CMND/CCCD hoặc Passport để xác minh danh tính.', 'CMND, CCCD, giấy tờ, ID, passport', 'booking', 7),
('Trẻ em có được miễn phí không?', 'Chính sách trẻ em:\n- Trẻ em dưới 5 tuổi: Miễn phí (ngủ chung giường với bố mẹ)\n- Trẻ em từ 5-12 tuổi: Có thể phụ thu (tùy loại phòng)\n- Trẻ em trên 12 tuổi: Tính như người lớn\n\nChi tiết sẽ được thông báo khi đặt phòng.', 'trẻ em, children, kids, bé, miễn phí trẻ em', 'booking', 7),
('Có phòng cho người khuyết tật không?', 'Có! Chúng tôi có phòng được thiết kế đặc biệt cho người khuyết tật với đầy đủ tiện ích phù hợp. Vui lòng liên hệ trước để chúng tôi chuẩn bị tốt nhất.', 'người khuyết tật, disabled, wheelchair, xe lăn', 'booking', 6),
('Có thể đặt phòng ngay hôm nay không?', 'Có! Bạn có thể đặt phòng ngay hôm nay nếu còn phòng trống. Vui lòng:\n1. Kiểm tra phòng còn trống trên website\n2. Đặt phòng online\n3. Hoặc gọi hotline để đặt nhanh', 'đặt ngay, đặt hôm nay, last minute, gấp', 'booking', 7),
('Có phòng view đẹp không?', 'Có! Chúng tôi có nhiều loại phòng với view khác nhau:\n- Phòng view thành phố\n- Phòng view sông\n- Phòng view vườn\n\nBạn có thể chọn khi đặt phòng hoặc yêu cầu khi check-in.', 'view, cảnh, view đẹp, phòng view', 'booking', 6),
('Có thể đặt phòng theo giờ không?', 'Hiện tại chúng tôi chỉ nhận đặt phòng theo đêm. Nếu bạn cần phòng theo giờ, vui lòng liên hệ trực tiếp để được tư vấn.', 'theo giờ, hourly, ngắn hạn, vài giờ', 'booking', 5),
('Đặt phòng có được xác nhận không?', 'Có! Sau khi đặt phòng thành công, bạn sẽ nhận được:\n- Email xác nhận\n- SMS xác nhận (nếu có số điện thoại)\n- Mã đặt phòng\n\nBạn có thể xem chi tiết trong "Lịch sử đặt phòng".', 'xác nhận, confirmation, mã đặt phòng, booking code', 'booking', 8),
('Có thể đặt phòng cho nhóm không?', 'Có! Chúng tôi hỗ trợ đặt phòng cho nhóm:\n- Nhóm nhỏ (2-4 người)\n- Nhóm lớn (5-10 người)\n- Đoàn (trên 10 người) - Có ưu đãi đặc biệt\n\nVui lòng liên hệ trực tiếp để được tư vấn tốt nhất.', 'nhóm, group, đoàn, team, nhiều người', 'booking', 7),
('Có phòng kết nối không?', 'Có! Chúng tôi có phòng kết nối (connecting rooms) phù hợp cho gia đình hoặc nhóm. Vui lòng liên hệ trực tiếp để đặt phòng kết nối.', 'phòng kết nối, connecting rooms, phòng liền', 'booking', 6),
('Có thể đặt phòng trước bao lâu?', 'Bạn có thể đặt phòng trước bất cứ lúc nào, không giới hạn thời gian. Tuy nhiên, để đảm bảo có phòng, nên đặt trước ít nhất 1-2 tuần, đặc biệt vào mùa cao điểm.', 'đặt trước, advance booking, bao lâu, sớm', 'booking', 6),

-- ========== GIÁ CẢ / THANH TOÁN (15 câu) ==========
('Giá phòng như thế nào?', 'Giá phòng tại Vĩnh Long Hotel rất đa dạng, phù hợp với mọi nhu cầu. Bạn có thể:\n- Xem giá chi tiết trên trang "Phòng"\n- Áp dụng mã giảm giá để tiết kiệm\n- Thành viên Silver/Gold/Platinum được giảm giá đặc biệt\n\nBạn muốn xem phòng nào cụ thể không?', 'giá, giá cả, price, cost, bao nhiêu tiền, giá phòng', 'payment', 10),
('Thanh toán như thế nào?', 'Chúng tôi hỗ trợ thanh toán qua:\n- QR Code (VietQR) - nhanh chóng và tiện lợi\n- Chuyển khoản ngân hàng\n- Tiền mặt tại khách sạn\n\nSau khi đặt phòng, bạn sẽ nhận được mã QR để quét và thanh toán ngay!', 'thanh toán, payment, pay, trả tiền, QR, chuyển khoản', 'payment', 10),
('Có thể thanh toán trả góp không?', 'Hiện tại chúng tôi chưa hỗ trợ thanh toán trả góp. Bạn có thể thanh toán một lần qua QR Code, chuyển khoản hoặc tiền mặt.', 'trả góp, installment, chia nhỏ, trả dần', 'payment', 5),
('Có phí phụ thu không?', 'Có thể có phí phụ thu trong các trường hợp:\n- Check-in sớm / Check-out muộn\n- Thêm người (vượt quá số lượng cho phép)\n- Dịch vụ đặc biệt\n\nTất cả phí phụ thu sẽ được thông báo rõ ràng khi đặt phòng.', 'phí phụ thu, extra fee, phụ phí, surcharge', 'payment', 7),
('Giá đã bao gồm thuế chưa?', 'Giá phòng hiển thị trên website đã bao gồm thuế VAT và các phí cơ bản. Bạn sẽ không phải trả thêm phí nào ngoài giá đã công bố (trừ các dịch vụ phụ thu tùy chọn).', 'thuế, VAT, tax, phí, giá đã bao gồm', 'payment', 8),
('Có thể thanh toán bằng thẻ tín dụng không?', 'Hiện tại chúng tôi hỗ trợ thanh toán qua QR Code (có thể dùng thẻ ngân hàng), chuyển khoản và tiền mặt. Thanh toán bằng thẻ tín dụng trực tiếp tại khách sạn có thể được hỗ trợ, vui lòng liên hệ trước.', 'thẻ tín dụng, credit card, thẻ, card', 'payment', 6),
('Có mã giảm giá không?', 'Có! Chúng tôi thường xuyên có các chương trình khuyến mãi:\n- Mã giảm giá theo mùa\n- Ưu đãi cho thành viên\n- Combo đặc biệt\n\nBạn có thể xem các mã giảm giá hiện có trên trang chủ!', 'mã giảm giá, voucher, discount, khuyến mãi, promo, coupon', 'payment', 9),
('Có thể đổi mã giảm giá không?', 'Mỗi đơn đặt phòng chỉ có thể sử dụng một mã giảm giá. Nếu bạn muốn đổi mã, vui lòng hủy đơn cũ và đặt lại với mã mới (nếu còn hiệu lực).', 'đổi mã, change voucher, thay mã giảm giá', 'payment', 5),
('Hoàn tiền như thế nào?', 'Nếu bạn hủy đặt phòng đúng chính sách (trước 24h), tiền sẽ được hoàn lại:\n- Thanh toán qua QR/Chuyển khoản: Hoàn về tài khoản trong 3-5 ngày làm việc\n- Thanh toán tiền mặt: Hoàn tại khách sạn\n\nVui lòng liên hệ để được hỗ trợ.', 'hoàn tiền, refund, trả lại tiền, hoàn phí', 'payment', 8),
('Có phí hủy phòng không?', 'Phí hủy phòng:\n- Hủy trước 24h: Miễn phí\n- Hủy trong vòng 24h: Có thể có phí (tùy loại phòng)\n- Sau thời gian check-in: Không hoàn tiền\n\nChi tiết sẽ được thông báo khi đặt phòng.', 'phí hủy, cancellation fee, phí cancel', 'payment', 7),
('Giá có thay đổi không?', 'Giá phòng có thể thay đổi tùy theo:\n- Mùa (cao điểm/thấp điểm)\n- Loại phòng\n- Thời gian đặt phòng\n\nGiá hiển thị trên website là giá cập nhật mới nhất. Giá có thể thay đổi mà không báo trước.', 'giá thay đổi, price change, biến động giá', 'payment', 6),
('Có ưu đãi cho khách quay lại không?', 'Có! Khách hàng quay lại sẽ được:\n- Tự động nâng hạng thành viên (nếu đủ điều kiện)\n- Nhận mã giảm giá đặc biệt\n- Ưu tiên phòng đẹp\n\nĐăng ký tài khoản để nhận ưu đãi!', 'khách quay lại, returning guest, repeat customer', 'payment', 6),
('Có thể thanh toán một phần không?', 'Tùy theo loại phòng và thời gian đặt, có thể yêu cầu đặt cọc một phần. Phần còn lại sẽ thanh toán khi check-in hoặc check-out. Chi tiết sẽ được thông báo khi đặt phòng.', 'thanh toán một phần, partial payment, đặt cọc', 'payment', 6),
('Có phí dịch vụ không?', 'Giá phòng đã bao gồm các dịch vụ cơ bản. Một số dịch vụ đặc biệt có thể phụ thu:\n- Spa & Massage\n- Dịch vụ giặt ủi\n- Mini bar\n\nTất cả sẽ được thông báo rõ ràng.', 'phí dịch vụ, service charge, phụ phí dịch vụ', 'payment', 6),
('Có thể thanh toán bằng ngoại tệ không?', 'Tại khách sạn, chúng tôi chỉ nhận thanh toán bằng VNĐ. Nếu bạn có ngoại tệ, vui lòng đổi sang VNĐ tại ngân hàng hoặc sử dụng thẻ quốc tế qua QR Code.', 'ngoại tệ, foreign currency, USD, EUR, đổi tiền', 'payment', 5),

-- ========== PHÒNG / TIỆN ÍCH (20 câu) ==========
('Có những tiện ích gì?', 'Khách sạn có đầy đủ tiện ích:\n- WiFi miễn phí\n- Bãi đỗ xe\n- Phòng gym\n- Nhà hàng\n- Spa & Massage\n- Hồ bơi\n- Dịch vụ giặt ủi\n\nBạn có thể xem chi tiết tại trang "Tiện ích"!', 'tiện ích, facilities, dịch vụ, amenities, có gì', 'room', 10),
('Phòng có WiFi không?', 'Có! Tất cả phòng đều có WiFi miễn phí tốc độ cao. Bạn sẽ nhận được mật khẩu WiFi khi check-in.', 'WiFi, wifi, internet, mạng, internet miễn phí', 'room', 9),
('Có bãi đỗ xe không?', 'Có! Khách sạn có bãi đỗ xe miễn phí cho khách lưu trú. Bãi đỗ xe có camera giám sát 24/7, đảm bảo an toàn cho phương tiện của bạn.', 'bãi đỗ xe, parking, đỗ xe, gửi xe, chỗ đậu xe', 'room', 9),
('Có hồ bơi không?', 'Có! Khách sạn có hồ bơi ngoài trời với view đẹp. Hồ bơi mở cửa từ 6:00 - 22:00 hàng ngày. Khách lưu trú được sử dụng miễn phí.', 'hồ bơi, swimming pool, pool, bể bơi', 'room', 8),
('Có phòng gym không?', 'Có! Khách sạn có phòng gym hiện đại với đầy đủ thiết bị. Phòng gym mở cửa 24/7, khách lưu trú được sử dụng miễn phí.', 'gym, phòng gym, thể dục, fitness, tập thể dục', 'room', 8),
('Có nhà hàng không?', 'Có! Khách sạn có nhà hàng phục vụ:\n- Bữa sáng buffet\n- Bữa trưa và tối (à la carte)\n- Đồ uống và snack\n\nNhà hàng mở cửa từ 6:00 - 22:00 hàng ngày.', 'nhà hàng, restaurant, ăn uống, buffet, bữa sáng', 'room', 8),
('Có Spa không?', 'Có! Khách sạn có Spa & Massage chuyên nghiệp với nhiều dịch vụ thư giãn. Bạn có thể đặt lịch trước hoặc khi check-in.', 'spa, massage, thư giãn, relax, chăm sóc sức khỏe', 'room', 7),
('Phòng có gì?', 'Mỗi phòng đều có:\n- Giường đôi/đơn tiêu chuẩn\n- Điều hòa\n- TV màn hình phẳng\n- WiFi miễn phí\n- Tủ lạnh mini\n- Phòng tắm riêng với đồ vệ sinh cá nhân\n- Ban công (một số phòng)', 'phòng có gì, tiện nghi phòng, đồ dùng trong phòng', 'room', 9),
('Có phòng tắm riêng không?', 'Có! Tất cả phòng đều có phòng tắm riêng với:\n- Vòi sen\n- Bồn tắm (một số phòng)\n- Đồ vệ sinh cá nhân\n- Máy sấy tóc\n- Khăn tắm', 'phòng tắm, bathroom, toilet, nhà vệ sinh', 'room', 8),
('Có minibar không?', 'Có! Mỗi phòng đều có tủ lạnh mini bar với đồ uống và snack. Sử dụng sẽ được tính phí. Bạn có thể yêu cầu làm đầy minibar khi cần.', 'minibar, mini bar, tủ lạnh, đồ uống trong phòng', 'room', 7),
('Có an ninh không?', 'Có! Khách sạn có hệ thống an ninh 24/7:\n- Camera giám sát\n- Bảo vệ túc trực\n- Thẻ từ phòng\n- Két an toàn trong phòng\n\nĐảm bảo an toàn tuyệt đối cho khách hàng.', 'an ninh, security, bảo vệ, an toàn, camera', 'room', 8),
('Có dịch vụ giặt ủi không?', 'Có! Chúng tôi có dịch vụ giặt ủi chuyên nghiệp:\n- Giặt ủi thường: 24h\n- Giặt ủi nhanh: 4h (phụ thu)\n\nBạn có thể yêu cầu dịch vụ qua điện thoại phòng hoặc lễ tân.', 'giặt ủi, laundry, giặt quần áo, ủi đồ', 'room', 7),
('Có dịch vụ đưa đón sân bay không?', 'Hiện tại chúng tôi chưa có dịch vụ đưa đón sân bay. Bạn có thể sử dụng taxi hoặc Grab. Chúng tôi có thể hỗ trợ gọi xe cho bạn.', 'đưa đón sân bay, airport transfer, đón sân bay', 'room', 5),
('Có thể nấu ăn trong phòng không?', 'Phòng không có bếp. Tuy nhiên, bạn có thể:\n- Sử dụng nhà hàng của khách sạn\n- Gọi đồ ăn về phòng (room service)\n- Đặt đồ ăn bên ngoài', 'nấu ăn, bếp, cooking, kitchen', 'room', 6),
('Có phòng hút thuốc không?', 'Khách sạn có khu vực hút thuốc riêng. Tất cả phòng nghỉ đều là phòng không hút thuốc để đảm bảo sức khỏe cho mọi khách hàng.', 'hút thuốc, smoking, phòng hút thuốc', 'room', 6),
('Có phòng cho thú cưng không?', 'Hiện tại chúng tôi chưa cho phép mang thú cưng vào khách sạn. Nếu bạn có nhu cầu đặc biệt, vui lòng liên hệ trước để được tư vấn.', 'thú cưng, pet, chó, mèo, động vật', 'room', 5),
('Có dịch vụ đặt tour không?', 'Có! Chúng tôi có thể hỗ trợ đặt tour tham quan các điểm du lịch Vĩnh Long. Vui lòng liên hệ lễ tân để được tư vấn và đặt tour.', 'tour, đặt tour, tham quan, du lịch', 'room', 6),
('Có dịch vụ thuê xe không?', 'Chúng tôi có thể hỗ trợ thuê xe máy hoặc xe ô tô cho khách hàng. Vui lòng liên hệ lễ tân để được tư vấn và đặt xe.', 'thuê xe, rent car, xe máy, ô tô', 'room', 6),
('Có phòng họp không?', 'Có! Khách sạn có phòng họp với sức chứa 20-50 người, trang bị đầy đủ thiết bị hiện đại. Vui lòng liên hệ trước để đặt phòng họp.', 'phòng họp, meeting room, hội nghị, seminar', 'room', 6),
('Có dịch vụ đổi tiền không?', 'Chúng tôi không có dịch vụ đổi tiền trực tiếp. Bạn có thể đổi tiền tại ngân hàng gần khách sạn hoặc sử dụng thẻ quốc tế qua QR Code.', 'đổi tiền, exchange, ngoại tệ', 'room', 5),

-- ========== ĐIỂM DU LỊCH (15 câu) ==========
('Có địa điểm du lịch nào gần đây không?', 'Vĩnh Long có nhiều điểm du lịch hấp dẫn:\n- Chùa Tiên Châu\n- Cù lao An Bình\n- Khu du lịch sinh thái Tràm Chim\n- Chợ nổi Cái Bè\n- Và nhiều điểm khác...\n\nBạn có thể xem chi tiết tại trang "Điểm đến"!', 'địa điểm, điểm du lịch, du lịch, destination, tham quan, nơi nào', 'destinations', 10),
('Chùa Tiên Châu', 'Chùa Tiên Châu là một trong những ngôi chùa cổ nổi tiếng của Vĩnh Long, cách khách sạn khoảng 5km. Chùa có kiến trúc độc đáo và không gian thanh tịnh, rất phù hợp để tham quan và cầu nguyện.', 'Chùa Tiên Châu, chùa, temple, pagoda', 'destinations', 8),
('Cù lao An Bình', 'Cù lao An Bình là điểm du lịch sinh thái nổi tiếng, cách khách sạn khoảng 10km. Nơi đây có vườn cây trái xanh mát, nhà vườn truyền thống và nhiều hoạt động giải trí thú vị.', 'Cù lao An Bình, cù lao, đảo, island', 'destinations', 8),
('Khu du lịch sinh thái Tràm Chim', 'Khu du lịch sinh thái Tràm Chim là điểm đến lý tưởng cho những ai yêu thiên nhiên, cách khách sạn khoảng 15km. Bạn có thể ngắm chim, đi thuyền và thưởng thức đặc sản địa phương.', 'Tràm Chim, sinh thái, eco-tourism, thiên nhiên', 'destinations', 8),
('Chợ nổi Cái Bè', 'Chợ nổi Cái Bè là một trong những chợ nổi lớn nhất miền Tây, cách khách sạn khoảng 20km. Đây là nơi bạn có thể trải nghiệm văn hóa sông nước miền Tây và mua đặc sản địa phương.', 'Chợ nổi Cái Bè, chợ nổi, floating market', 'destinations', 8),
('Có thể đi tour một ngày không?', 'Có! Bạn có thể tham quan nhiều điểm du lịch trong một ngày. Chúng tôi có thể hỗ trợ đặt tour hoặc bạn có thể tự thuê xe. Các điểm gần khách sạn có thể đi trong 1-2 giờ.', 'tour một ngày, day trip, tham quan một ngày', 'destinations', 7),
('Khoảng cách đến các điểm du lịch', 'Khoảng cách từ khách sạn:\n- Chùa Tiên Châu: ~5km (10 phút)\n- Cù lao An Bình: ~10km (20 phút)\n- Tràm Chim: ~15km (30 phút)\n- Chợ nổi Cái Bè: ~20km (40 phút)\n\nTất cả đều có thể đi bằng xe máy hoặc taxi.', 'khoảng cách, distance, bao xa, cách bao nhiêu', 'destinations', 7),
('Có thể thuê xe đi tham quan không?', 'Có! Chúng tôi có thể hỗ trợ thuê xe máy hoặc xe ô tô để đi tham quan. Bạn cũng có thể sử dụng Grab hoặc taxi. Vui lòng liên hệ lễ tân để được hỗ trợ.', 'thuê xe, rent, đi tham quan, phương tiện', 'destinations', 7),
('Điểm du lịch nào gần nhất?', 'Điểm du lịch gần khách sạn nhất là Chùa Tiên Châu, chỉ cách khoảng 5km (10 phút đi xe). Đây là điểm đến lý tưởng cho chuyến tham quan ngắn.', 'gần nhất, closest, gần khách sạn', 'destinations', 6),
('Có đặc sản gì ở các điểm du lịch?', 'Tại các điểm du lịch, bạn có thể mua:\n- Bưởi Năm Roi\n- Bánh tráng nem Lai Vung\n- Nem Lai Vung\n- Các loại trái cây miền Tây\n- Đồ lưu niệm\n\nBạn có thể xem chi tiết tại trang "Điểm đến" phần "Đặc sản"!', 'đặc sản, specialty, quà lưu niệm, mua gì', 'destinations', 7),
('Có thể đi thuyền không?', 'Có! Tại các điểm du lịch như Cù lao An Bình và Tràm Chim, bạn có thể đi thuyền tham quan. Dịch vụ này thường được bao gồm trong tour hoặc có thể đặt riêng.', 'đi thuyền, boat, thuyền, sông nước', 'destinations', 6),
('Thời gian tốt nhất để tham quan', 'Thời gian tốt nhất để tham quan Vĩnh Long:\n- Sáng sớm (6-9h): Mát mẻ, ít người\n- Chiều muộn (16-18h): Không nắng gắt\n- Tránh giờ trưa (11-14h): Nắng nóng\n\nMùa khô (tháng 12-4) là thời điểm lý tưởng nhất.', 'thời gian tốt, best time, khi nào đi', 'destinations', 6),
('Có thể đi bộ đến điểm du lịch không?', 'Một số điểm như Chùa Tiên Châu có thể đi bộ (khoảng 1 giờ), nhưng khuyến nghị nên đi bằng xe máy hoặc taxi để tiết kiệm thời gian và sức lực. Các điểm khác cần phương tiện.', 'đi bộ, walking, có thể đi bộ không', 'destinations', 5),
('Có hướng dẫn viên không?', 'Chúng tôi có thể hỗ trợ tìm hướng dẫn viên địa phương cho bạn. Hướng dẫn viên sẽ giúp bạn hiểu rõ hơn về văn hóa và lịch sử của các điểm du lịch. Vui lòng liên hệ trước.', 'hướng dẫn viên, tour guide, guide, dẫn tour', 'destinations', 6),
('Có thể chụp ảnh không?', 'Có! Bạn có thể chụp ảnh tại tất cả các điểm du lịch. Tuy nhiên, một số khu vực trong chùa có thể yêu cầu không chụp ảnh. Vui lòng tuân thủ quy định của từng địa điểm.', 'chụp ảnh, photo, selfie, ảnh', 'destinations', 5),

-- ========== ĐẶC SẢN (15 câu) ==========
('Có đặc sản Vĩnh Long không?', 'Có! Vĩnh Long nổi tiếng với nhiều đặc sản:\n- Bánh tráng nem Lai Vung\n- Nem Lai Vung\n- Bưởi Năm Roi\n- Cá tai tượng chiên xù\n- Chả giò rế\n- Khoai lang Bình Tân\n- Thanh trà\n- Tôm càng xanh\n\nBạn có thể xem chi tiết tại trang "Điểm đến" phần "Đặc sản Vĩnh Long"!', 'đặc sản, specialty, món ăn, quà lưu niệm, có gì', 'general', 9),
('Bánh tráng nem Lai Vung', 'Bánh tráng nem Lai Vung là đặc sản nổi tiếng của Vĩnh Long, được làm từ gạo, có độ dẻo dai và hương vị đặc trưng. Thường dùng để cuốn nem, gỏi cuốn hoặc ăn kèm các món nướng. Giá: 20.000 - 30.000 VNĐ/xấp.', 'Bánh tráng nem, bánh tráng, nem Lai Vung', 'general', 8),
('Nem Lai Vung', 'Nem Lai Vung là món ăn truyền thống, nổi tiếng khắp miền Tây. Nem có vị chua, cay, mặn, ngọt hài hòa, được làm từ thịt heo tươi, bì heo và các gia vị đặc trưng. Giá: 50.000 - 100.000 VNĐ/chục.', 'Nem Lai Vung, nem, nem chua', 'general', 8),
('Bưởi Năm Roi', 'Bưởi Năm Roi là loại trái cây đặc sản của Vĩnh Long, nổi tiếng với múi bưởi to, mọng nước, vị ngọt thanh và không hạt. Bưởi có vỏ mỏng, dễ bóc. Giá: 30.000 - 80.000 VNĐ/quả.', 'Bưởi Năm Roi, bưởi, trái cây', 'general', 8),
('Mua đặc sản ở đâu?', 'Bạn có thể mua đặc sản Vĩnh Long tại:\n- Chợ nổi Cái Bè\n- Các cửa hàng đặc sản trong thành phố\n- Các điểm du lịch\n- Cửa hàng tại khách sạn (một số loại)\n\nBạn có thể xem danh sách cửa hàng tại trang "Điểm đến" phần "Đặc sản"!', 'mua ở đâu, where to buy, cửa hàng, shop', 'general', 7),
('Có thể mua đặc sản làm quà không?', 'Có! Đặc sản Vĩnh Long rất phù hợp làm quà tặng. Nhiều cửa hàng có dịch vụ đóng gói đẹp và gửi hàng đi các tỉnh. Bạn có thể đặt hàng trước để đảm bảo có sẵn.', 'quà tặng, gift, làm quà, đóng gói', 'general', 7),
('Giá đặc sản', 'Giá đặc sản Vĩnh Long:\n- Bánh tráng nem: 20.000 - 30.000 VNĐ/xấp\n- Nem Lai Vung: 50.000 - 100.000 VNĐ/chục\n- Bưởi Năm Roi: 30.000 - 80.000 VNĐ/quả\n- Cá tai tượng: 150.000 - 250.000 VNĐ/con\n\nGiá có thể thay đổi tùy theo mùa và địa điểm mua.', 'giá đặc sản, price, bao nhiêu tiền', 'general', 7),
('Có thể ship đặc sản không?', 'Một số cửa hàng đặc sản có dịch vụ ship hàng đi các tỉnh. Bạn có thể liên hệ trực tiếp với cửa hàng hoặc chúng tôi có thể hỗ trợ tìm cửa hàng có dịch vụ này.', 'ship, gửi hàng, delivery, vận chuyển', 'general', 6),
('Đặc sản nào nổi tiếng nhất?', 'Đặc sản nổi tiếng nhất của Vĩnh Long là:\n1. Nem Lai Vung\n2. Bánh tráng nem Lai Vung\n3. Bưởi Năm Roi\n\nĐây là những món được nhiều du khách yêu thích và thường mua làm quà.', 'nổi tiếng nhất, popular, best, phổ biến', 'general', 7),
('Có thể thử đặc sản tại khách sạn không?', 'Một số đặc sản có thể được phục vụ tại nhà hàng khách sạn. Bạn có thể yêu cầu khi đặt bàn hoặc check-in. Chúng tôi sẽ cố gắng đáp ứng yêu cầu của bạn.', 'thử tại khách sạn, ăn tại hotel, restaurant', 'general', 6),
('Đặc sản nào phù hợp làm quà?', 'Đặc sản phù hợp làm quà:\n- Bánh tráng nem (dễ bảo quản, đóng gói đẹp)\n- Nem Lai Vung (đặc trưng, nổi tiếng)\n- Bưởi Năm Roi (tươi ngon, đẹp mắt)\n- Các loại mứt trái cây\n\nTất cả đều có thể đóng gói đẹp để làm quà.', 'quà tặng, gift, phù hợp, suitable', 'general', 6),
('Có tour tham quan làng nghề đặc sản không?', 'Có thể! Chúng tôi có thể hỗ trợ đặt tour tham quan các làng nghề làm đặc sản như làng làm bánh tráng, làng làm nem. Bạn sẽ được xem quy trình sản xuất và mua sản phẩm tươi ngon. Vui lòng liên hệ trước.', 'làng nghề, craft village, tour làng nghề', 'general', 6),
('Đặc sản nào có thể bảo quản lâu?', 'Đặc sản có thể bảo quản lâu:\n- Bánh tráng nem (bảo quản khô, để được vài tháng)\n- Nem Lai Vung (bảo quản lạnh, để được vài tuần)\n- Các loại mứt (để được vài tháng)\n- Bưởi Năm Roi (để được vài tuần ở nhiệt độ thường)', 'bảo quản, storage, để được bao lâu', 'general', 6),
('Có đặc sản chay không?', 'Có! Một số đặc sản phù hợp cho người ăn chay:\n- Bánh tráng nem (làm từ gạo)\n- Các loại trái cây\n- Các loại mứt trái cây\n\nBạn có thể hỏi cửa hàng để được tư vấn cụ thể.', 'chay, vegetarian, đồ chay', 'general', 5),
('Có thể đặt đặc sản trước không?', 'Có! Bạn có thể đặt đặc sản trước để đảm bảo có sẵn, đặc biệt vào mùa cao điểm. Một số cửa hàng có dịch vụ đặt hàng online hoặc qua điện thoại. Chúng tôi có thể hỗ trợ liên hệ.', 'đặt trước, pre-order, order, đặt hàng', 'general', 6),

-- ========== KHÁC (5 câu) ==========
('Cảm ơn', 'Không có gì! 😊 Nếu bạn cần thêm thông tin gì, cứ hỏi tôi nhé! Tôi luôn sẵn sàng hỗ trợ bạn!', 'cảm ơn, thanks, thank you, thank', 'general', 5),
('Tạm biệt', 'Tạm biệt! Chúc bạn có một ngày tuyệt vời! Nếu cần hỗ trợ gì thêm, cứ quay lại chat với tôi nhé! 👋', 'tạm biệt, goodbye, bye, see you', 'general', 5),
('Không hiểu', 'Xin lỗi vì tôi chưa hiểu rõ câu hỏi của bạn. Bạn có thể:\n- Diễn đạt lại câu hỏi\n- Hỏi về các chủ đề: đặt phòng, giá cả, tiện ích, điểm du lịch, thanh toán\n- Liên hệ trực tiếp với chúng tôi qua hotline', 'không hiểu, không biết, unclear, confused', 'general', 4),
('Cần giúp đỡ', 'Tôi luôn sẵn sàng giúp đỡ bạn! Bạn có thể hỏi tôi về:\n- Đặt phòng\n- Giá cả và thanh toán\n- Tiện ích khách sạn\n- Điểm du lịch Vĩnh Long\n- Đặc sản địa phương\n\nHoặc liên hệ trực tiếp với chúng tôi!', 'cần giúp, help, hỗ trợ, support', 'general', 5),
('Làm sao liên hệ admin?', 'Để liên hệ với admin hoặc nhân viên hỗ trợ:\n- Hotline: Xem trên trang "Liên hệ"\n- Email: Xem trên trang "Liên hệ"\n- Chat trực tuyến: Nếu câu hỏi phức tạp, tôi sẽ chuyển bạn sang admin\n- Trực tiếp tại khách sạn', 'liên hệ admin, contact admin, nhân viên, staff', 'general', 6);

-- ============================================
-- KẾT THÚC
-- ============================================

