/**
 * Language Translations
 * Hỗ trợ Tiếng Việt và English
 */

const translations = {
  vi: {
    // Navigation
    'nav.home': 'Trang chủ',
    'nav.rooms': 'Phòng',
    'nav.facilities': 'Tiện ích',
    'nav.destinations': 'Điểm đến & đặc sản',
    'nav.about': 'Về chúng tôi',
    'nav.contact': 'Liên hệ',
    
    // Auth
    'auth.login': 'Đăng nhập',
    'auth.register': 'Đăng ký',
    'auth.owner': 'Chủ KS',
    'auth.logout': 'Đăng xuất',
    'auth.profile': 'Hồ sơ & bảo mật',
    'auth.bookings': 'Lịch sử đặt phòng',
    'auth.messages': 'Tin nhắn',
    'auth.paymentHistory': 'Lịch sử thanh toán',
    'auth.loginOther': 'Đăng nhập tài khoản khác',
    'auth.ownerLogin': 'Đăng nhập Chủ khách sạn',
    'auth.loginTitle': 'Đăng nhập tài khoản',
    'auth.emailOrPhone': 'Email hoặc số điện thoại',
    'auth.emailOrPhonePlaceholder': 'Nhập email hoặc số điện thoại',
    'auth.password': 'Mật khẩu',
    'auth.passwordPlaceholder': 'Nhập mật khẩu',
    'auth.forgotPassword': 'Quên mật khẩu?',
    'auth.or': 'Hoặc',
    'auth.savedAccounts': 'Tài khoản đã lưu',
    'auth.processing': 'Đang xử lý...',
    'auth.noAccount': 'Chưa có tài khoản?',
    'auth.haveAccount': 'Đã có tài khoản?',
    'auth.registerNow': 'Đăng ký ngay',
    'auth.loginNow': 'Đăng nhập ngay',
    'auth.registerTitle': 'Tạo tài khoản mới',
    'auth.fullName': 'Họ và tên',
    'auth.fullNamePlaceholder': 'Nhập họ và tên',
    'auth.email': 'Email',
    'auth.emailPlaceholder': 'Nhập email',
    'auth.emailVerified': 'Email đã được xác thực',
    'auth.phone': 'Số điện thoại',
    'auth.phonePlaceholder': 'Nhập số điện thoại (VD: 0987654321)',
    'auth.phoneInfo': 'Số điện thoại Việt Nam (10 số, bắt đầu bằng 0)',
    'auth.dateOfBirth': 'Ngày sinh',
    'auth.ageRequirement': 'Phải từ 18 tuổi trở lên',
    'auth.gender': 'Giới tính',
    'auth.address': 'Địa chỉ',
    'auth.addressPlaceholder': 'Nhập địa chỉ',
    'auth.confirmPassword': 'Xác nhận mật khẩu',
    'auth.confirmPasswordPlaceholder': 'Nhập lại mật khẩu',
    'auth.otpNote': 'Lưu ý: Mã xác thực sẽ được gửi tự động khi bạn ấn nút "Đăng ký"',
    'auth.sendOTP': 'Gửi mã xác thực',
    
    // Chat Widget
    'chat.onlineSupport': 'Hỗ trợ trực tuyến',
    'chat.readyToSupport': 'Sẵn sàng hỗ trợ',
    'chat.connecting': 'Đang kết nối...',
    'chat.minimize': 'Thu nhỏ',
    'chat.close': 'Đóng',
    'chat.openChat': 'Mở chat',
    'chat.adminAccess': 'Admin đã truy cập cuộc trò chuyện này',
    'chat.hello': 'Xin chào! 👋',
    'chat.assistantIntro': 'Tôi là trợ lý ảo của Vĩnh Long Hotel. Tôi có thể giúp bạn:',
    'chat.quickBooking': 'Đặt phòng',
    'chat.quickPricing': 'Giá cả',
    'chat.quickFacilities': 'Tiện ích',
    'chat.quickDestinations': 'Điểm đến',
    'chat.messagePlaceholder': 'Nhập tin nhắn của bạn...',
    'chat.send': 'Gửi',
    'chat.loginToUse': 'Đăng nhập để sử dụng chat',
    'chat.autoMessage': 'Tin nhắn tự động',
    'chat.staffMessage': 'Nhân viên hỗ trợ',
    'chat.bookingMessage': 'Tôi muốn đặt phòng',
    'chat.pricingMessage': 'Giá phòng như thế nào?',
    'chat.facilitiesMessage': 'Có những tiện ích gì?',
    'chat.destinationsMessage': 'Có địa điểm du lịch nào gần đây không?',
    'auth.lastBooking': 'Đơn gần nhất',
    'auth.tierProgress': 'Tiến độ thăng hạng',
    'tier.memberProgram': 'Chương trình thành viên',
    'tier.newMember': 'Thành viên mới',
    'tier.silverTier': 'Hạng Silver',
    'tier.goldTier': 'Hạng Gold',
    'tier.platinumTier': 'Hạng Platinum',
    'tier.discount': 'Giảm',
    'tier.condition': 'Điều kiện',
    'tier.conditionNewMember': 'Chưa đặt phòng lần nào',
    'tier.conditionSilver': 'Đã đặt phòng từ 1 lần',
    'tier.conditionGold': 'Đã đặt phòng từ 5 lần',
    'tier.conditionPlatinum': 'Đã đặt phòng từ 10 lần',
    'tier.note': 'Lưu ý',
    'tier.noteText': 'Ưu đãi giảm giá sẽ được áp dụng tự động khi đặt phòng. Phần trăm giảm giá được tính trên tổng giá phòng trước thuế và phí dịch vụ.',
    
    // Common
    'common.search': 'Tìm kiếm',
    'common.book': 'Đặt phòng',
    'common.view': 'Xem chi tiết',
    'common.readMore': 'Đọc thêm',
    'common.learnMore': 'Tìm hiểu thêm',
    'common.explore': 'Khám phá',
    'common.close': 'Đóng',
    'common.save': 'Lưu',
    'common.cancel': 'Hủy',
    'common.submit': 'Gửi',
    'common.loading': 'Đang tải...',
    'common.error': 'Có lỗi xảy ra',
    'common.success': 'Thành công',
    'common.sorry': 'Xin lỗi',
    'common.tryAgain': 'Vui lòng thử lại',
    'common.connectionError': 'Không thể kết nối đến server',
    
    // Hero Section
    'hero.title': 'Khám phá Vĩnh Long',
    'hero.subtitle': 'Trải nghiệm nghỉ dưỡng tuyệt vời',
    'hero.search': 'Tìm kiếm phòng',
    
    // Rooms
    'rooms.title': 'Phòng nghỉ',
    'rooms.available': 'Còn phòng',
    'rooms.soldOut': 'Hết phòng',
    'rooms.price': 'Giá từ',
    'rooms.perNight': '/đêm',
    'rooms.viewDetails': 'Xem chi tiết',
    
    // Facilities
    'facilities.title': 'Tiện ích',
    'facilities.description': 'Khám phá các tiện ích hiện đại',
    'facilities.subtitle': 'TIỆN NGHI & DỊCH VỤ',
    'facilities.intro': 'Khách sạn Vĩnh Long Hotel mang đến hệ thống tiện nghi hiện đại và cao cấp bậc nhất, đáp ứng mọi nhu cầu nghỉ dưỡng của quý khách. <br>Từ Wi-Fi tốc độ cao, máy lạnh, truyền hình và máy nước nóng, đến minibar, ấm đun nước, bàn làm việc, tủ quần áo, gương toàn thân hay bàn ủi – tất cả đều được trang bị chu đáo nhằm mang lại sự thoải mái tuyệt đối. <br>Quý khách có thể thư giãn tại spa chuyên nghiệp, tận hưởng không gian ban công thoáng mát, hay đắm mình trong bồn tắm riêng sang trọng. <br>Vĩnh Long Hotel tự hào mang đến trải nghiệm lưu trú trọn vẹn, tiện nghi và đẳng cấp, giúp quý khách cảm nhận sự khác biệt trong từng khoảnh khắc nghỉ ngơi.',
    
    // Destinations
    'destinations.title': 'Điểm đến & Đặc sản',
    'destinations.description': 'Khám phá vẻ đẹp Vĩnh Long',
    'destinations.pageTitle': 'Điểm đến Vĩnh Long',
    'destinations.subtitle': 'KHÁM PHÁ VĨNH LONG',
    'destinations.heading': 'ĐIỂM ĐẾN DU LỊCH VĨNH LONG',
    'destinations.intro': 'Vĩnh Long tự hào sở hữu nhiều điểm đến du lịch hấp dẫn, từ những ngôi chùa cổ kính, cù lao xanh tươi, đến các khu du lịch sinh thái và chợ nổi sầm uất. Khám phá vẻ đẹp văn hóa và thiên nhiên độc đáo của vùng đất Nam Bộ, và tìm những phòng nghỉ gần nhất để có trải nghiệm trọn vẹn.',
    'destinations.searchPlaceholder': 'Tìm kiếm điểm đến, địa danh, vị trí...',
    'destinations.searchButton': 'Tìm kiếm',
    'destinations.searchSuggestions': 'Gợi ý tìm kiếm',
    'destinations.searchHistory': 'Lịch sử tìm kiếm',
    'destinations.sortBy': 'Sắp xếp theo:',
    'destinations.sortRatingDesc': 'Đánh giá cao nhất',
    'destinations.sortRatingAsc': 'Đánh giá thấp nhất',
    'destinations.sortNameAsc': 'Tên A-Z',
    'destinations.sortNameDesc': 'Tên Z-A',
    'destinations.sortReviewsDesc': 'Nhiều đánh giá nhất',
    'destinations.foundResults': 'Tìm thấy',
    'destinations.destinations': 'điểm du lịch',
    'destinations.all': 'Tất cả',
    'destinations.categoryTemple': 'Chùa, Đình',
    'destinations.categoryNature': 'Thiên nhiên',
    'destinations.categoryMarket': 'Chợ nổi',
    'destinations.categoryCulture': 'Văn hóa',
    'destinations.categoryOther': 'Khác',
    'destinations.viewDetails': 'Xem chi tiết',
    'destinations.images': 'ảnh',
    'destinations.reviews': 'đánh giá',
    'destinations.noResults': 'Không tìm thấy điểm du lịch',
    'destinations.noResultsDesc': 'Vui lòng thử lại với bộ lọc khác.',
    'destinations.specialtiesSubtitle': 'ĐẶC SẢN ĐỊA PHƯƠNG',
    'destinations.specialtiesHeading': 'ĐẶC SẢN VĨNH LONG',
    'destinations.specialtiesIntro': 'Khám phá những món ăn, trái cây và quà lưu niệm đặc trưng của vùng đất Vĩnh Long',
    'destinations.specialtyCategoryFood': 'Món ăn',
    'destinations.specialtyCategoryFruit': 'Trái cây',
    'destinations.specialtyCategoryDrink': 'Đồ uống',
    'destinations.specialtyCategorySouvenir': 'Quà lưu niệm',
    'destinations.specialtyCategoryDefault': 'Đặc sản',
    'destinations.noSpecialties': 'Chưa có thông tin đặc sản',
    'destinations.noSpecialtiesDesc': 'Thông tin đặc sản sẽ được cập nhật sớm.',
    'destinations.loading': 'Đang tải...',
    'destinations.searching': 'Đang tìm kiếm...',
    
    // Destination Details
    'destinationDetails.pageTitle': 'Chi tiết điểm du lịch',
    'destinationDetails.home': 'Trang chủ',
    'destinationDetails.destinations': 'Điểm đến',
    'destinationDetails.viewAllImages': 'Xem tất cả hình ảnh',
    'destinationDetails.address': 'Địa chỉ',
    'destinationDetails.coordinates': 'Tọa độ',
    'destinationDetails.viewNearbyRooms': 'Xem phòng gần đây',
    'destinationDetails.share': 'Chia sẻ',
    'destinationDetails.facebook': 'Facebook',
    'destinationDetails.print': 'In',
    'destinationDetails.backToList': 'Quay lại danh sách',
    'destinationDetails.introduction': 'Giới thiệu',
    'destinationDetails.summary': 'Tóm tắt',
    'destinationDetails.map': 'Bản đồ',
    'destinationDetails.viewLargeMap': 'Xem bản đồ lớn',
    'destinationDetails.nearbyRooms': 'Phòng nghỉ gần đây',
    'destinationDetails.noNearbyRooms': 'Chưa có phòng nghỉ gần điểm du lịch này.',
    'destinationDetails.kmAway': 'Cách',
    'destinationDetails.perNight': '/đêm',
    'destinationDetails.viewRoom': 'Xem phòng',
    'destinationDetails.similarDestinations': 'Điểm đến tương tự',
    'destinationDetails.viewDetails': 'Xem chi tiết',
    'destinationDetails.destinationImages': 'Hình của điểm du lịch',
    'destinationDetails.allImages': 'Tất cả hình ảnh',
    'destinationDetails.image': 'Ảnh',
    'destinationDetails.reviews': 'đánh giá',
    'specialtyDetails.home': 'Trang chủ',
    'specialtyDetails.destinations': 'Điểm đến',
    'specialtyDetails.price': 'Giá',
    'specialtyDetails.bestSeason': 'Mùa tốt nhất',
    'specialtyDetails.location': 'Địa điểm',
    'specialtyDetails.rating': 'Đánh giá',
    'specialtyDetails.reviews': 'đánh giá',
    'specialtyDetails.viewOnMap': 'Xem trên bản đồ',
    'specialtyDetails.getDirections': 'Chỉ đường',
    'specialtyDetails.buyLocations': 'Địa điểm mua',
    'specialtyDetails.contact': 'Liên hệ',
    'specialtyDetails.address': 'Địa chỉ',
    'specialtyDetails.phone': 'Điện thoại',
    'specialtyDetails.website': 'Website',
    'specialtyDetails.giftSuggestion': 'Gợi ý quà lưu niệm',
    'specialtyDetails.openingHours': 'Giờ mở cửa',
    'destinations.clearHistoryConfirm': 'Bạn có chắc muốn xóa lịch sử tìm kiếm?',
    'destinations.noSuggestions': 'Không tìm thấy gợi ý',
    'destinations.caiBeFloatingMarket': 'Chợ nổi Cái Bè',
    'destinations.tienChauTemple': 'Chùa Tiên Châu',
    'destinations.anBinhIsland': 'Cù lao An Bình',
    'destinations.binhHoaPhuoc': 'Khu du lịch Bình Hòa Phước',
    'destinations.tramChimEco': 'Khu du lịch sinh thái Tràm Chim',
    'destinations.longHoVillage': 'Làng nghề đan lát Long Hồ',
    'destinations.caiMonOrchard': 'Vườn cây trái Cái Mơn',
    'destinations.longThanhTemple': 'Đình Long Thanh',
    
    // About
    'about.pageTitle': 'Về chúng tôi',
    'about.subtitle': 'GIỚI THIỆU',
    'about.heading': 'VỀ CHÚNG TÔI',
    'about.studentInfo': 'Sinh viên K22 - Đại học Trà Vinh - Khoa Công nghệ Thông tin',
    'about.introTitle': 'Lời Giới Thiệu',
    'about.intro1': 'Chúng tôi là nhóm sinh viên K22 – Đại học Trà Vinh, Khoa Công nghệ Thông Tin, những người trẻ đầy nhiệt huyết và quyết tâm mang đến các sản phẩm phần mềm chất lượng, sáng tạo và hữu ích. Mỗi thành viên đều có thế mạnh riêng, nhưng chúng tôi cùng chung một mục tiêu: học hỏi, phát triển và tạo ra giá trị thực tế thông qua công nghệ.',
    'about.intro2': 'Với tinh thần trách nhiệm, sự nghiêm túc trong học tập và niềm đam mê với lập trình, nhóm luôn cố gắng hoàn thiện bản thân từng ngày và mang đến những sản phẩm sáng tạo, tối ưu và thân thiện với người dùng.',
    'about.intro3': 'Chúng tôi tin rằng:',
    'about.introQuote': 'Công nghệ là công cụ – con người mới là giá trị cốt lõi.',
    'about.statRooms': '100+ PHÒNG',
    'about.statCustomers': '200+ KHÁCH HÀNG',
    'about.statReviews': '150+ ĐÁNH GIÁ',
    'about.statStaff': '50+ NHÂN SỰ',
    'about.teamTitle': 'Admin VĩnhLongHotel',
    'about.logoAlt': 'Logo Đại học Trà Vinh',
    'about.siteAbout': '',
    
    // Testimonials
    'testimonials.title': 'Khách hàng nói gì',
    'testimonials.subtitle': 'Những đánh giá từ khách hàng thực tế',
    
    // Footer
    'footer.newsletter.title': 'Luôn được cập nhật các gợi ý & khuyến mãi mới nhất',
    'footer.newsletter.description': 'Nhập email để nhận ưu đãi mới nhất',
    'footer.newsletter.placeholder': 'Nhập email của bạn',
    'footer.newsletter.submit': 'Đăng ký',
    'footer.newsletter.sending': 'Đang gửi...',
    'footer.app.title': 'Có chuyến đi mơ ước của bạn trong tầm tay',
    'footer.app.description': 'Tải ứng dụng và nhận ưu đãi',
    'footer.trust.security': 'Bảo mật',
    'footer.trust.support': 'Hỗ trợ 24/7',
    'footer.trust.price': 'Giá tốt',
    'footer.payment.title': 'Đối tác thanh toán',
    
    // Language
    'language.toggle': 'Chuyển đổi ngôn ngữ',
    'language.vi': 'Tiếng Việt',
    'language.en': 'English',
    
    // Contact
    'contact.title': 'Liên hệ',
    'contact.name': 'Họ tên',
    'contact.email': 'Email',
    'contact.phone': 'Số điện thoại',
    'contact.subject': 'Chủ đề',
    'contact.message': 'Tin nhắn',
    'contact.send': 'Gửi tin nhắn',
    
    // Booking
    'booking.checkIn': 'Nhận phòng',
    'booking.checkOut': 'Trả phòng',
    'booking.guests': 'Số khách',
    'booking.search': 'Tìm kiếm',
    'confirmBooking.room': 'Phòng',
    'confirmBooking.available': 'Còn',
    'confirmBooking.rooms': 'phòng',
    'confirmBooking.adults': 'người lớn',
    'confirmBooking.children': 'trẻ em',
    'confirmBooking.freeWifi': 'WiFi miễn phí',
    'confirmBooking.view': 'View thoáng',
    'confirmBooking.amenities': 'Tiện ích',
    'confirmBooking.map': 'Bản đồ',
    'confirmBooking.priceFrom': 'Giá/phòng/đêm từ',
    'confirmBooking.originalPrice': 'Giá gốc',
    'confirmBooking.bookNow': 'Đặt ngay',
    'confirmBooking.step1': 'Chọn ngày',
    'confirmBooking.step1Desc': 'Kiểm tra phòng trống',
    'confirmBooking.step2': 'Thông tin khách',
    'confirmBooking.step2Desc': 'Liên hệ & yêu cầu',
    'confirmBooking.step3': 'Thanh toán',
    'confirmBooking.step3Desc': 'Xác nhận QR',
    'confirmBooking.hotelMap': 'Bản đồ khách sạn',
    'confirmBooking.allImages': 'Tất cả hình ảnh',
    'confirmBooking.images': 'ảnh',
    'confirmBooking.viewAllImages': 'Xem tất cả hình ảnh',
    'confirmBooking.overview': 'Tổng quan phòng',
    'confirmBooking.capacity': 'Sức chứa',
    'confirmBooking.area': 'Diện tích',
    'confirmBooking.status': 'Tình trạng',
    'confirmBooking.mainFacilities': 'Tiện ích chính',
    'confirmBooking.fullAC': 'Điều hòa đầy đủ',
    'confirmBooking.optionalBreakfast': 'Bữa sáng tuỳ chọn',
    'confirmBooking.readMore': 'Xem thêm',
    'confirmBooking.readLess': 'Thu gọn',
    'confirmBooking.reception24': 'Lễ tân 24/7',
    'confirmBooking.nearby': 'Lân cận',
    'confirmBooking.nightMarket': 'Chợ đêm / Chợ trung tâm',
    'confirmBooking.cathedral': 'Nhà thờ lớn',
    'confirmBooking.station': 'Ga trung tâm',
    'confirmBooking.supermarket': 'Siêu thị & tiện ích',
    'confirmBooking.reviewsFromGuests': 'Đánh giá từ khách',
    'confirmBooking.step2And3': 'Bước 2 & 3',
    'confirmBooking.bookingDetails': 'Chi tiết đặt phòng',
    'confirmBooking.discountApplied': 'Giá ưu đãi đã áp dụng',
    'confirmBooking.fullName': 'Họ và tên',
    'confirmBooking.phone': 'Số điện thoại',
    'confirmBooking.address': 'Địa chỉ',
    'confirmBooking.checkInDate': 'Ngày nhận phòng',
    'confirmBooking.checkOutDate': 'Ngày trả phòng',
    'confirmBooking.promoCode': 'Mã giảm giá',
    'confirmBooking.enterPromoCode': 'Nhập mã giảm giá',
    'confirmBooking.apply': 'Áp dụng',
    'confirmBooking.selectSavedCode': 'Chọn mã đã lưu',
    'confirmBooking.savedFromHome': 'Mã đã lưu từ trang chủ (nút "Lưu" ở danh sách mã).',
    'confirmBooking.specialRequest': 'Yêu cầu đặc biệt (tuỳ chọn)',
    'confirmBooking.specialRequestPlaceholder': 'VD: Phòng tầng cao, view sông...',
    'confirmBooking.checkAvailability': 'Kiểm tra phòng trống & tính phí tự động sau khi chọn ngày.',
    'confirmBooking.upcomingBookings': 'Trạng thái đặt phòng sắp tới',
    'confirmBooking.noBookings': 'Chưa có lịch đặt nào. Bạn có thể chọn ngày phù hợp.',
    'confirmBooking.pending': 'chờ xác nhận',
    'confirmBooking.booked': 'đã đặt',
    'confirmBooking.roomPrice': 'Giá phòng',
    'confirmBooking.loyaltyDiscount': 'Giảm hạng',
    'confirmBooking.tax': 'Thuế (8%)',
    'confirmBooking.serviceFee': 'Phí dịch vụ (2%)',
    'confirmBooking.discount': 'Giảm giá',
    'confirmBooking.total': 'Tổng thanh toán',
    'confirmBooking.scanQR': 'Quét mã bằng ứng dụng ngân hàng/MoMo/ZaloPay.',
    'confirmBooking.amount': 'Số tiền',
    'confirmBooking.selectDatesAndConfirm': 'Chọn ngày và xác nhận QR để mở nút đặt phòng.',
    'confirmBooking.paymentInfo': 'Chọn ngày nhận/trả phòng, sau đó chạm đúp vào mã QR để mở nút thanh toán.',
    'confirmBooking.paymentButtonHint': 'Nút thanh toán sẽ mở khi: đã chọn ngày hợp lệ, còn phòng, và xác nhận đã quét QR.',
    'confirmBooking.payNow': 'Thanh toán ngay',
    'confirmBooking.doubleTapQR': 'Chạm đúp để xác nhận',
    'confirmBooking.copied': '✓ Đã sao chép',
    'confirmBooking.copyInfo': 'Sao chép thông tin',
    'confirmBooking.copyPaymentInfo': 'Đã sao chép thông tin thanh toán',
    'confirmBooking.cannotCopy': 'Không thể sao chép',
    'confirmBooking.noReviews': 'Chưa có đánh giá nào!',
    'confirmBooking.adminReply': 'Phản hồi từ chủ khách sạn',
    'confirmBooking.helpful': 'Đánh dấu hữu ích',
    'confirmBooking.thankYouReview': 'Cảm ơn bạn đã để lại đánh giá!',
    'confirmBooking.noSavedPromos': 'Chưa lưu mã',
    'confirmBooking.maxDiscount': 'tối đa',
    'confirmBooking.minOrder': 'Đơn tối thiểu',
    'confirmBooking.noMinRequired': 'Không yêu cầu tối thiểu',
    'confirmBooking.savedCode': 'Mã đã lưu',
    
    // Bookings
    'bookings.pageTitle': 'Lịch sử đặt phòng',
    'bookings.home': 'Trang chủ',
    'bookings.bookingHistory': 'Lịch sử đặt phòng',
    'bookings.noBookings': 'Chưa có đặt phòng nào',
    'bookings.noBookingsDesc': 'Bạn chưa có lịch sử đặt phòng. Hãy đặt phòng ngay để trải nghiệm dịch vụ của chúng tôi!',
    'bookings.viewRooms': 'Xem phòng trống',
    'bookings.checkIn': 'Nhận phòng',
    'bookings.checkOut': 'Trả phòng',
    'bookings.nights': 'Số đêm',
    'bookings.totalAmount': 'Tổng tiền',
    'bookings.paymentMethod': 'Thanh toán bằng',
    'bookings.orderId': 'Mã đơn',
    'bookings.bookingDate': 'Ngày đặt',
    'bookings.address': 'Địa chỉ',
    'bookings.roomNumber': 'Số phòng',
    'bookings.statusBooked': 'Đã đặt phòng',
    'bookings.statusCancelled': 'Đã hủy phòng',
    'bookings.statusPending': 'Đang chờ',
    'bookings.statusProcessing': 'Đang xử lý',
    'bookings.statusCancelledBadge': 'Đã hủy',
    'bookings.paymentNotPaid': 'Chưa thanh toán',
    'bookings.paymentQR': 'QR Code / VietQR',
    'bookings.paymentMoMo': 'MoMo',
    'bookings.paymentZaloPay': 'ZaloPay',
    'bookings.paymentBank': 'Chuyển khoản ngân hàng',
    'bookings.paymentCard': 'Thẻ tín dụng/Ghi nợ',
    'bookings.paymentProcessing': 'Đang xử lý',
    'bookings.requirement': 'Yêu cầu',
    'bookings.promoCode': 'Mã',
    'bookings.refunding': 'Đang hoàn tiền',
    'bookings.refunded': 'Đã hoàn tiền',
    'bookings.yourReview': 'Đánh giá của bạn',
    'bookings.adminReply': 'Phản hồi từ quản trị viên',
    'bookings.review': 'Đánh giá',
    'bookings.cancel': 'Hủy đặt',
    'bookings.reviewAndComment': 'Đánh giá & Nhận xét',
    'bookings.rating': 'Đánh giá',
    'bookings.comment': 'Nhận xét',
    'bookings.reviewImages': 'Ảnh đánh giá (tối đa 5 ảnh, mỗi ảnh tối đa 5MB)',
    'bookings.acceptFormats': 'Chấp nhận: JPG, PNG, WEBP',
    'bookings.selectRating': '-- Chọn đánh giá --',
    'bookings.rating5': '⭐ 5 - Xuất sắc',
    'bookings.rating4': '⭐ 4 - Tốt',
    'bookings.rating3': '⭐ 3 - Bình thường',
    'bookings.rating2': '⭐ 2 - Kém',
    'bookings.rating1': '⭐ 1 - Tệ',
    'bookings.reviewPlaceholder': 'Chia sẻ trải nghiệm của bạn về phòng này...',
    'bookings.cancelBtn': 'Hủy',
    'bookings.submitReview': 'Gửi đánh giá',
    'bookings.perNight': '/ đêm',
    'bookings.nightsUnit': 'đêm',
    
    // Profile
    'profile.pageTitle': 'Hồ sơ cá nhân',
    'profile.home': 'Trang chủ',
    'profile.profile': 'Hồ sơ cá nhân',
    'profile.myInfo': 'Thông tin của tôi',
    'profile.basicInfo': 'Thông tin cơ bản',
    'profile.name': 'Tên',
    'profile.email': 'Email',
    'profile.changeEmail': 'Đổi email',
    'profile.password': 'Mật khẩu',
    'profile.forgotPassword': 'Quên mật khẩu?',
    'profile.forgotPasswordDesc': 'Nhấn để nhận mã OTP đặt lại mật khẩu',
    'profile.phone': 'Số điện thoại',
    'profile.dob': 'Ngày tháng năm sinh',
    'profile.idNumber': 'Mã định danh',
    'profile.gender': 'Giới tính',
    'profile.selectGender': '-- Chọn giới tính --',
    'profile.male': 'Nam',
    'profile.female': 'Nữ',
    'profile.address': 'Địa chỉ',
    'profile.saveChanges': 'Lưu thay đổi',
    'profile.avatar': 'Ảnh đại diện',
    'profile.selectNewImage': 'Chọn ảnh mới',
    'profile.imageSupport': 'Hỗ trợ: JPG, PNG, WEBP',
    'profile.changePassword': 'Đổi mật khẩu',
    'profile.oldPassword': 'Mật khẩu cũ',
    'profile.newPassword': 'Mật khẩu mới',
    'profile.confirmPassword': 'Xác nhận mật khẩu mới',
    'profile.enterCurrentPassword': 'Nhập mật khẩu hiện tại',
    'profile.enterNewPassword': 'Nhập mật khẩu mới',
    'profile.reEnterNewPassword': 'Nhập lại mật khẩu mới',
    'profile.currentPasswordDesc': 'Vui lòng nhập mật khẩu hiện tại để xác thực',
    'profile.minPasswordLength': 'Tối thiểu 6 ký tự',
    'profile.passwordMatch': 'Phải khớp với mật khẩu mới',
    'profile.cancel': 'Hủy',
    'profile.favorites': 'Yêu thích',
    'profile.noFavorites': 'Chưa có phòng yêu thích nào',
    'profile.addToFavorites': 'Thêm vào yêu thích',
    'profile.list': 'Danh sách',
    'profile.details': 'Chi tiết',
    'profile.bookNow': 'Đặt ngay',
    'profile.adults': 'người lớn',
    'profile.children': 'trẻ em',
    'profile.night': 'đêm',
    'profile.removeFavorite': 'Bỏ yêu thích',
    'profile.pleaseEnterNewEmail': 'Vui lòng nhập email mới!',
    'profile.invalidEmail': 'Email không hợp lệ!',
    'profile.newEmailMustDifferent': 'Email mới phải khác email hiện tại!',
    'profile.otpSent': 'Mã xác thực đã được gửi đến email mới của bạn!',
    'profile.emailAlreadyUsed': 'Email này đã được sử dụng!',
    'profile.sessionExpired': 'Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại!',
    'profile.userNotFound': 'Không tìm thấy thông tin người dùng!',
    'profile.otpSendFailed': 'Không thể gửi mã xác thực. Vui lòng kiểm tra cấu hình email hoặc thử lại sau!',
    'profile.emailChangedSuccess': 'Đổi email thành công!',
    'profile.otpExpired': 'Mã xác thực đã hết hạn. Vui lòng gửi lại mã!',
    'profile.updateSuccess': 'Cập nhật thành công!',
    'profile.updateFailed': 'Cập nhật thất bại!',
    'profile.avatarUpdateSuccess': 'Cập nhật ảnh đại diện thành công!',
    'profile.pleaseFillAllFields': 'Vui lòng điền đầy đủ thông tin!',
    'profile.phoneAlreadyRegistered': 'Số điện thoại này đã được đăng ký!',
    'profile.loginToUseFavorites': 'Vui lòng đăng nhập để sử dụng yêu thích',
    'profile.favoriteUpdateError': 'Có lỗi khi cập nhật yêu thích',
    'profile.sending': 'Đang gửi...',
    'profile.errorOccurred': 'Có lỗi xảy ra',
    
    // Payment History
    'paymentHistory.pageTitle': 'Lịch sử thanh toán',
    'paymentHistory.home': 'Trang chủ',
    'paymentHistory.paymentHistory': 'Lịch sử thanh toán',
    'paymentHistory.totalPaid': 'Tổng đã thanh toán',
    'paymentHistory.totalTransactions': 'Tổng giao dịch',
    'paymentHistory.noPayments': 'Chưa có lịch sử thanh toán',
    'paymentHistory.noPaymentsDesc': 'Bạn chưa có giao dịch thanh toán nào. Hãy đặt phòng và thanh toán để xem lịch sử tại đây!',
    'paymentHistory.orderId': 'Mã đơn',
    'paymentHistory.paymentDate': 'Ngày thanh toán',
    'paymentHistory.status': 'Trạng thái',
    'paymentHistory.amount': 'Số tiền',
    'paymentHistory.roomName': 'Tên phòng',
    'paymentHistory.checkIn': 'Nhận phòng',
    'paymentHistory.checkOut': 'Trả phòng',
    'paymentHistory.statusSuccess': 'Thành công',
    'paymentHistory.statusPending': 'Đang chờ',
    'paymentHistory.statusFailed': 'Thất bại',
    'paymentHistory.viewDetails': 'Xem chi tiết',
    'paymentHistory.transactionId': 'Mã giao dịch',
    'paymentHistory.nights': 'Số đêm',
    'paymentHistory.pricePerNight': 'Giá/đêm',
    'paymentHistory.booking': 'Đặt phòng',
    'paymentHistory.nightsUnit': 'đêm',
    
    // Messages
    'messages.pageTitle': 'Tin nhắn',
    'messages.messages': 'Tin nhắn',
    'messages.admin': 'Quản trị viên',
    'messages.enterMessage': 'Nhập tin nhắn...',
    'messages.send': 'Gửi',
    'messages.noMessages': 'Chưa có tin nhắn nào. Hãy bắt đầu cuộc trò chuyện!',
    'messages.autoMessage': 'Tin nhắn tự động',
    'messages.sendError': 'Có lỗi xảy ra khi gửi tin nhắn',
    'messages.conversations': 'Cuộc trò chuyện',
    'messages.selectConversation': 'Chọn một cuộc trò chuyện để bắt đầu',
    
    // Reviews
    'reviews.title': 'Đánh giá',
    'reviews.write': 'Viết đánh giá',
    'reviews.rating': 'Đánh giá',
    'reviews.comment': 'Bình luận',
    
    // Hero Section
    'hero.experience': 'Trải nghiệm sang trọng giữa lòng Vĩnh Long',
    'hero.title': 'Khách sạn nghỉ dưỡng sang trọng giá hấp dẫn',
    'hero.description': 'Chọn phòng chuẩn 4-5★, ưu đãi QR, hỗ trợ 24/7.',
    'hero.exploreRooms': 'Khám phá phòng',
    'hero.viewPromos': 'Xem ưu đãi',
    'hero.carouselSubtitle': 'Trải nghiệm lưu trú 4–5★ tại Vĩnh Long',
    
    // Search Box
    'search.location': 'Địa điểm',
    'search.checkIn': 'Nhận phòng',
    'search.checkOut': 'Trả phòng',
    'search.guests': 'Người lớn & Trẻ em',
    'search.stars': 'Số sao',
    'search.search': 'Tìm kiếm',
    'search.selectLocation': 'Chọn địa điểm',
    'search.selectGuests': 'Chọn số khách',
    'search.selectStars': 'Chọn số sao',
    'search.area': 'Khu vực Vĩnh Long',
    'search.selectArea': 'Tất cả khu vực',
    'search.adults': 'Người lớn',
    'search.children': 'Trẻ em',
    'search.adultsDesc': 'Từ 13 tuổi trở lên',
    'search.childrenDesc': 'Độ tuổi dưới 12',
    'search.clear': 'Xóa',
    'search.apply': 'Áp dụng',
    'search.selectDatesHint': 'Vui lòng chọn đủ ngày nhận phòng và ngày trả phòng',
    'search.selectGuestsHint': 'Vui lòng chọn ít nhất 1 người lớn',
    
    // Sections
    'section.rooms': 'Danh sách phòng',
    'section.roomsDesc': 'Chọn phòng phù hợp với nhu cầu của bạn',
    'section.facilities': 'Tiện ích nổi bật',
    'section.destinations': 'Điểm đến & Đặc sản',
    'section.testimonials': 'Khách hàng nói gì',
    'section.testimonialsDesc': 'Những đánh giá từ khách hàng thực tế',
    'section.whyChoose': 'Lý do nên đặt phòng với Vĩnh Long Hotel?',
    'section.stats': 'Hơn 10,000 lượt đặt phòng, hơn 5,000 đánh giá',
    'section.rating': 'Đánh giá',
    'section.satisfied': 'Hài lòng',
    
    // Why Choose Cards
    'why.meetNeeds': 'Đáp ứng mọi nhu cầu của bạn',
    'why.meetNeedsDesc': 'Từ phòng nghỉ, tiện ích, đến điểm tham quan, bạn có thể tin chọn dịch vụ hoàn chỉnh và hướng dẫn du lịch của chúng tôi.',
    'why.flexibleBooking': 'Tùy chọn đặt phòng linh hoạt',
    'why.flexibleBookingDesc': 'Kế hoạch thay đổi bất ngờ? Đừng lo! Đổi lịch hoặc Hoàn tiền dễ dàng.',
    'why.safePayment': 'Thanh toán an toàn và thuận tiện',
    'why.safePaymentDesc': 'Tận hưởng nhiều cách thanh toán an toàn, bằng loại tiền thuận tiện nhất cho bạn.',
    'why.quality': 'Chất lượng dịch vụ 5 sao',
    'why.qualityDesc': 'Phòng nghỉ tiện nghi, dịch vụ chuyên nghiệp, đạt tiêu chuẩn quốc tế và được khách hàng đánh giá cao.',
    
    // Room Cards
    'room.viewDetails': 'Xem chi tiết',
    'room.perNight': '/đêm',
    'room.popular': 'Phổ biến',
    'room.discount': 'Giảm giá',
    
    // Rooms Page
    'rooms.explore': 'Khám phá Vĩnh Long',
    'rooms.quickSearch': 'Tìm nhanh phòng còn trống, giá tốt, đủ tiện ích',
    'rooms.filterDesc': 'Lọc theo ngày, hạng sao, tiện ích và số khách để đặt phòng chuẩn nhu cầu.',
    'rooms.filters': 'Bộ lọc',
    'rooms.clearAll': 'Xóa tất cả',
    'rooms.search': 'Tìm kiếm',
    'rooms.searchPlaceholder': 'Nhập tên phòng hoặc mô tả...',
    'rooms.area': 'Khu vực Vĩnh Long',
    'rooms.allDistricts': 'Tất cả quận/huyện',
    'rooms.priceRange': 'Khoảng giá (VND/đêm)',
    'rooms.all': 'Tất cả',
    'rooms.checkAvailability': 'Kiểm tra phòng trống',
    'rooms.refresh': 'Làm mới',
    'rooms.guestsCount': 'Số lượng khách',
    'rooms.space': 'Không gian',
    'rooms.new': 'Mới',
    'rooms.freeCancel': 'Hủy miễn phí',
    'rooms.priceNote': 'Giá cho 1 đêm đã gồm thuế/phí cơ bản',
    'rooms.temporarilyClosed': 'Tạm ngưng',
    'rooms.nearDestinations': 'Phòng gần điểm du lịch',
    'rooms.noDestinations': 'Chưa có điểm du lịch nào',
    'rooms.sort': 'Sắp xếp',
    'rooms.sortDefault': 'Mặc định',
    'rooms.sortPriceAsc': 'Giá tăng dần',
    'rooms.sortPriceDesc': 'Giá giảm dần',
    'rooms.filterKeyword': 'Từ khóa',
    'rooms.filterArea': 'Khu vực',
    'rooms.star': 'sao',
    'rooms.filterPrice': 'Giá',
    'rooms.filterStay': 'Lưu trú',
    'rooms.filterGuests': 'Khách',
    'rooms.filterFacilities': 'Tiện ích',
    'rooms.filterDestinations': 'Điểm du lịch',
    'rooms.sortLowHigh': 'Giá thấp → cao',
    'rooms.sortHighLow': 'Giá cao → thấp',
    'rooms.noFiltersHint': 'Chọn bộ lọc để tìm phòng nhanh hơn',
    'rooms.loading': 'Đang tải...',
    'rooms.searching': 'Đang tìm kiếm phòng phù hợp...',
    'rooms.noRating': 'Chưa có đánh giá',
    'rooms.bookNow': 'Đặt ngay',
    'rooms.details': 'Chi tiết',
    'rooms.prev': 'Trước',
    'rooms.next': 'Sau',
    'rooms.showing': 'Hiển thị',
    'rooms.ofTotal': 'trong tổng số',
    'rooms.noRoomsFound': 'Không có phòng phù hợp!',
    
    // Reviews
    'reviews.noRating': 'Chưa có đánh giá',
    
    // Promos
    'promo.title': 'Mã giảm giá hấp dẫn',
    'promo.offers': 'Ưu đãi',
    'promo.onlineOnly': 'Chỉ áp dụng khi đặt phòng online',
    'promo.copyAll': 'Copy tất cả',
    'promo.copyAllTitle': 'Copy tất cả mã giảm giá',
    'promo.codeLabel': 'Mã giảm giá',
    'promo.copy': 'Sao chép',
    'promo.save': 'Lưu',
    'promo.saveTitle': 'Lưu mã này',
    'promo.expires': 'Hết hạn',
    'promo.unlimited': 'Không giới hạn',
    'promo.expiresIn2Days': 'Hết hạn sau 2 ngày',
    'promo.expiresIn': 'Còn',
    'promo.expired': 'Đã hết hạn',
    'promo.runningOut': 'Sắp hết mã',
    'promo.limited': 'Có hạn',
    'promo.bankOffer': 'Ưu đãi ngân hàng',
    'promo.qrPayment': 'Thanh toán QR',
    'promo.hotDestination': 'Điểm đến hot',
    
    // Reviews
    'reviews.feelings': 'Cảm nhận',
    'reviews.fromGuests': 'Đánh giá từ khách',
    'reviews.total': 'Tổng đánh giá',
    'reviews.average': 'Điểm trung bình',
    'reviews.satisfied': 'Khách hàng hài lòng',
    'reviews.viewAll': 'Xem tất cả đánh giá',
    'reviews.updating': 'Đang cập nhật đánh giá từ khách hàng.',
    'reviews.guest': 'Khách hàng',
    'reviews.noReview': 'Chưa có đánh giá chi tiết.',
    'reviews.verified': 'Khách hàng đã xác thực',
    'reviews.today': 'Hôm nay',
    'reviews.yesterday': 'Hôm qua',
    'reviews.daysAgo': 'ngày trước',
    'reviews.weeksAgo': 'tuần trước',
    'reviews.monthsAgo': 'tháng trước',
    'reviews.yearsAgo': 'năm trước',
    
    // Room
    'room.viewAll': 'Xem tất cả phòng',
    'room.viewRoom': 'Xem phòng',
    'room.discountPercent': 'Giảm',
    'room.adults': 'người lớn',
    'room.children': 'trẻ em',
    'room.updating': 'Đang cập nhật',
    'room.updatingFacilities': 'Đang cập nhật tiện ích',
    'room.bookNow': 'Đặt ngay',
    'room.soldOut': 'Hết phòng',
    'room.details': 'Chi tiết',
    'roomDetails.pageTitle': 'Chi tiết phòng',
    'roomDetails.home': 'Trang chủ',
    'roomDetails.roomList': 'Danh sách phòng',
    'roomDetails.adults': 'người lớn',
    'roomDetails.children': 'trẻ em',
    'roomDetails.postedBy': 'Đăng bởi',
    'roomDetails.admin': 'Quản trị viên hệ thống',
    'roomDetails.owner': 'Chủ khách sạn',
    'roomDetails.message': 'Nhắn tin',
    'roomDetails.priceFrom': 'Giá từ',
    'roomDetails.originalPrice': 'Giá gốc',
    'roomDetails.discount': 'Giảm',
    'roomDetails.perNight': '/ đêm',
    'roomDetails.description': 'Mô tả phòng',
    'roomDetails.readMore': 'Xem thêm',
    'roomDetails.readLess': 'Thu gọn',
    'roomDetails.nearbyDestinations': 'Điểm du lịch gần đây',
    'roomDetails.viewDetails': 'Xem chi tiết',
    'roomDetails.viewAllDestinations': 'Xem tất cả điểm du lịch',
    'roomDetails.noNearbyDestinations': 'Chưa có thông tin điểm du lịch gần phòng này.',
    'roomDetails.exploreDestinations': 'Khám phá điểm du lịch Vĩnh Long',
    'roomDetails.relatedRooms': 'Phòng tương tự',
    'roomDetails.viewAllRooms': 'Xem tất cả phòng',
    'roomDetails.noRelatedRooms': 'Chưa có phòng tương tự.',
    'roomDetails.exploreRooms': 'Khám phá tất cả phòng',
    'roomDetails.customerExperience': 'Trải nghiệm khách hàng',
    'roomDetails.noReviews': 'Chưa có đánh giá nào!',
    'roomDetails.adminReply': 'Phản hồi từ chủ khách sạn',
    'roomDetails.helpful': 'Đánh dấu hữu ích',
    'roomDetails.priceSummary': 'Tóm tắt giá',
    'roomDetails.nights': 'đêm',
    'roomDetails.roomPrice': 'Giá phòng',
    'roomDetails.tax': 'Thuế (8%)',
    'roomDetails.serviceFee': 'Phí dịch vụ (2%)',
    'roomDetails.subtotal': 'Tạm tính',
    'roomDetails.space': 'Không gian',
    'roomDetails.facilities': 'Tiện ích',
    'roomDetails.noInfo': 'Chưa có thông tin',
    'roomDetails.capacity': 'Sức chứa & diện tích',
    'roomDetails.bookNow': 'Đặt ngay',
    'roomDetails.soldOut': 'Hết phòng',
    'roomDetails.available': 'Còn',
    'roomDetails.rooms': 'phòng',
    'roomDetails.location': 'Vị trí',
    'roomDetails.viewLargeMap': 'Xem bản đồ lớn',
    'roomDetails.kmAway': 'Cách',
    'roomDetails.km': 'km',
    'room.features': 'Đặc điểm nổi bật',
    'room.remaining': 'Còn',
    'room.rooms': 'phòng',
    'room.reviewFrom': 'Đánh giá từ phòng',
    'room.space': 'Không gian',
    'room.facilities': 'Tiện ích',
    
    // Features (Tiện nghi trong phòng)
    'features.bedroom': 'Phòng Ngủ',
    'features.balcony': 'Ban Công',
    'features.kitchen': 'Nhà Bếp',
    'features.sofa': 'Ghế Sofa',
    'features.bathroom': 'Phòng Tắm',
    'features.livingRoom': 'Phòng Khách',
    'features.refrigerator': 'Tủ Lạnh',
    'features.airConditioner': 'Máy Lạnh',
    'features.tv': 'TV',
    'features.wifi': 'WiFi',
    
    // Facilities
    'facilities.viewMore': 'Xem thêm tiện ích',
    'facilities.wifi': 'Wi-Fi',
    'facilities.tv': 'Truyền Hình',
    'facilities.spa': 'Spa',
    'facilities.heater': 'Máy Sưởi',
    'facilities.heaterDesc': 'Hệ thống sưởi ấm giúp khách hàng tận hưởng không gian ấm áp trong mùa lạnh.',
    'facilities.airConditioner': 'Máy Lạnh',
    'facilities.waterHeater': 'Máy Nước Nóng',
    'facilities.hairDryer': 'Máy Sấy Tóc',
    'facilities.personalHygiene': 'Đồ Vệ Sinh Cá Nhân',
    'facilities.minibar': 'Minibar',
    'facilities.kettle': 'Ấm Đun Nước',
    'facilities.workspace': 'Khu Làm Việc',
    'facilities.wardrobe': 'Tủ Quần Áo',
    'facilities.slippers': 'Dép Đi Trong Nhà',
    'facilities.fullMirror': 'Gương Toàn Thân',
    'facilities.iron': 'Bàn Ủi',
    'facilities.bar': 'Quầy bar',
    'facilities.barDesc': 'Quầy bar sang trọng đa dạng đồ uống, phục vụ khách hàng thư giãn buổi tối.',
    'facilities.golfCourse': 'Sân golf',
    'facilities.golfCourseDesc': 'Sân golf gần khách sạn, khu vực giải trí cao cấp.',
    'facilities.swimmingPool': 'Hồ bơi',
    'facilities.swimmingPoolDesc': 'Hồ bơi ngoài trời, nước trong xanh, thích hợp để thư giãn hoặc bơi lội.',
    'facilities.airportShuttle': 'Xe đưa đón sân bay',
    'facilities.airportShuttleDesc': 'Dịch vụ đưa đón sân bay nhanh chóng, tiện lợi và an toàn.',
    'facilities.service24': 'Dịch vụ 24/24 giờ',
    'facilities.service24Desc': 'Dịch vụ lễ tân 24/24, luôn sẵn sàng hỗ trợ mọi nhu cầu của khách hàng.',
    'facilities.freeWifi': 'WiFi miễn phí',
    'facilities.parking': 'Bãi đỗ xe',
    'facilities.restaurant': 'Nhà hàng',
    'facilities.gym': 'Phòng gym',
    'facilities.laundry': 'Dịch vụ giặt ủi',
    
    // Contact
    'contact.support247': 'Hỗ trợ 24/7',
    'contact.readyToHelp': 'Chúng tôi luôn sẵn sàng hỗ trợ bạn mọi lúc',
    'contact.hotelLocation': 'Vị trí khách sạn',
    'contact.viewLargeMap': 'Xem bản đồ lớn',
    'contact.address': 'Địa chỉ',
    'contact.directions': 'Chỉ đường',
    'contact.guide': 'Hướng dẫn',
    'contact.guide1': 'Dễ dàng tìm thấy từ trung tâm thành phố',
    'contact.guide2': 'Có bãi đỗ xe miễn phí',
    'contact.guide3': 'Gần các điểm du lịch nổi tiếng',
    'contact.nearby': 'Điểm gần đây',
    'contact.transportation': 'Giao thông',
    'contact.transport1': 'Có bãi đỗ xe',
    'contact.transport2': 'Dễ gọi taxi',
    'contact.transport3': 'Có thể đi bộ từ trung tâm',
    'contact.quickConnect': 'Kết nối nhanh',
    'contact.hotline': 'Hotline',
    'contact.workingHours': 'Giờ làm việc',
    'contact.hours247': 'Thứ 2 - Chủ nhật: 24/7',
    'contact.supportAnytime': 'Hỗ trợ khách hàng mọi lúc',
    'contact.followUs': 'Theo dõi chúng tôi',
    'contact.sendMessage': 'Gửi tin nhắn',
    'contact.responseTime': 'Phản hồi trong vòng 1 giờ',
    'contact.leaveMessage': 'Để lại lời nhắn',
    'contact.response24h': 'Chúng tôi sẽ phản hồi trong vòng 24 giờ',
    'contact.nameLabel': 'Tên',
    'contact.emailLabel': 'Email',
    'contact.subjectLabel': 'Tiêu đề',
    'contact.messageLabel': 'Nội dung',
    'contact.namePlaceholder': 'Nhập tên của bạn',
    'contact.subjectPlaceholder': 'Tiêu đề tin nhắn',
    'contact.messagePlaceholder': 'Nhập nội dung tin nhắn của bạn...',
    'contact.minChars': 'Tối thiểu 10 ký tự',
    'contact.copyPhone': 'Sao chép số điện thoại',
    'contact.copyEmail': 'Sao chép email',
    'contact.copied': 'Đã sao chép!',
    'contact.sending': 'Đang gửi...',
    'contact.viewMap': 'Xem vị trí trên bản đồ',
    'contact.nightMarket': 'Chợ đêm',
    'contact.cathedral': 'Nhà thờ lớn',
    'contact.station': 'Ga trung tâm',
    'contact.supermarket': 'Siêu thị',
    'contact.km': 'km',
    'contact.m': 'm',
    
    // Footer
    'footer.exploreBook': 'Khám phá & đặt phòng Vĩnh Long',
    'footer.partner': 'Hợp tác với',
    'footer.about': 'Về Vĩnh Long Hotel',
    'footer.howToBook': 'Cách đặt chỗ',
    'footer.contactUs': 'Liên hệ chúng tôi',
    'footer.products': 'Sản phẩm',
    'footer.hotels': 'Khách sạn',
    'footer.flights': 'Vé máy bay',
    'footer.bus': 'Vé xe khách',
    'footer.cruises': 'Du thuyền',
    'footer.villas': 'Biệt thự',
    'footer.apartments': 'Căn hộ',
    'footer.forOwners': 'Dành cho Chủ khách sạn',
    'footer.registerAccount': 'Đăng ký tài khoản',
    'footer.ownerLogin': 'Đăng nhập quản lý',
    'footer.manageHotel': 'Quản lý khách sạn của bạn',
    'footer.contactSupport': 'Liên hệ hỗ trợ',
    'footer.others': 'Khác',
    'footer.affiliate': 'Vĩnh Long Hotel Affiliate',
    'footer.referFriends': 'Giới thiệu bạn bè',
    'footer.blog': 'Vĩnh Long Hotel Blog',
    'footer.privacy': 'Chính Sách Quyền Riêng',
    'footer.terms': 'Điều khoản & Điều kiện',
    'footer.press': 'Khu vực báo chí',
    'footer.regulations': 'Quy chế hoạt động',
    'footer.followUs': 'Theo dõi chúng tôi',
    'footer.downloadApp': 'Tải ứng dụng',
  },
  
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.rooms': 'Rooms',
    'nav.facilities': 'Facilities',
    'nav.destinations': 'Destinations & Specialties',
    'nav.about': 'About Us',
    'nav.contact': 'Contact',
    
    // Auth
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.owner': 'Owner',
    'auth.logout': 'Logout',
    'auth.profile': 'Profile & Security',
    'auth.bookings': 'Booking History',
    'auth.messages': 'Messages',
    'auth.paymentHistory': 'Payment History',
    'auth.loginOther': 'Login with another account',
    'auth.ownerLogin': 'Hotel Owner Login',
    'auth.loginTitle': 'Login to Account',
    'auth.emailOrPhone': 'Email or Phone Number',
    'auth.emailOrPhonePlaceholder': 'Enter email or phone number',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': 'Enter password',
    'auth.forgotPassword': 'Forgot password?',
    'auth.or': 'Or',
    'auth.savedAccounts': 'Saved Accounts',
    'auth.processing': 'Processing...',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.haveAccount': 'Already have an account?',
    'auth.registerNow': 'Register now',
    'auth.loginNow': 'Login now',
    'auth.registerTitle': 'Create New Account',
    'auth.fullName': 'Full Name',
    'auth.fullNamePlaceholder': 'Enter full name',
    'auth.email': 'Email',
    'auth.emailPlaceholder': 'Enter email',
    'auth.emailVerified': 'Email verified',
    'auth.phone': 'Phone Number',
    'auth.phonePlaceholder': 'Enter phone number (e.g., 0987654321)',
    'auth.phoneInfo': 'Vietnamese phone number (10 digits, starting with 0)',
    'auth.dateOfBirth': 'Date of Birth',
    'auth.ageRequirement': 'Must be 18 years or older',
    'auth.gender': 'Gender',
    'auth.address': 'Address',
    'auth.addressPlaceholder': 'Enter address',
    'auth.confirmPassword': 'Confirm Password',
    'auth.confirmPasswordPlaceholder': 'Re-enter password',
    'auth.otpNote': 'Note: Verification code will be sent automatically when you click "Register"',
    'auth.sendOTP': 'Send verification code',
    
    // Chat Widget
    'chat.onlineSupport': 'Online Support',
    'chat.readyToSupport': 'Ready to support',
    'chat.connecting': 'Connecting...',
    'chat.minimize': 'Minimize',
    'chat.close': 'Close',
    'chat.openChat': 'Open chat',
    'chat.adminAccess': 'Admin has accessed this conversation',
    'chat.hello': 'Hello! 👋',
    'chat.assistantIntro': 'I am the virtual assistant of Vinh Long Hotel. I can help you:',
    'chat.quickBooking': 'Book a room',
    'chat.quickPricing': 'Prices',
    'chat.quickFacilities': 'Amenities',
    'chat.quickDestinations': 'Destinations',
    'chat.messagePlaceholder': 'Enter your message...',
    'chat.send': 'Send',
    'chat.loginToUse': 'Log in to use chat',
    'chat.autoMessage': 'Auto message',
    'chat.staffMessage': 'Support staff',
    'chat.bookingMessage': 'I want to book a room',
    'chat.pricingMessage': 'What are the room prices?',
    'chat.facilitiesMessage': 'What amenities are available?',
    'chat.destinationsMessage': 'Are there any tourist destinations nearby?',
    'auth.lastBooking': 'Last booking',
    'auth.tierProgress': 'Tier progress',
    'tier.memberProgram': 'Member Program',
    'tier.newMember': 'New Member',
    'tier.silverTier': 'Silver Tier',
    'tier.goldTier': 'Gold Tier',
    'tier.platinumTier': 'Platinum Tier',
    'tier.discount': 'Off',
    'tier.condition': 'Condition',
    'tier.conditionNewMember': 'No bookings made yet',
    'tier.conditionSilver': 'Booked 1 time or more',
    'tier.conditionGold': 'Booked 5 times or more',
    'tier.conditionPlatinum': 'Booked 10 times or more',
    'tier.note': 'Note',
    'tier.noteText': 'Discount offers will be applied automatically when booking. The discount percentage is calculated on the total room price before tax and service fees.',
    
    // Common
    'common.search': 'Search',
    'common.book': 'Book Now',
    'common.view': 'View Details',
    'common.readMore': 'Read More',
    'common.learnMore': 'Learn More',
    'common.explore': 'Explore',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.submit': 'Submit',
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.success': 'Success',
    'common.sorry': 'Sorry',
    'common.tryAgain': 'Please try again',
    'common.connectionError': 'Unable to connect to server',
    
    // Hero Section
    'hero.title': 'Discover Vinh Long',
    'hero.subtitle': 'Experience wonderful accommodation',
    'hero.search': 'Search Rooms',
    'hero.experience': 'Luxury experience in the heart of Vinh Long',
    'hero.description': 'Choose 4-5★ standard rooms, QR offers, 24/7 support.',
    'hero.exploreRooms': 'Explore Rooms',
    'hero.viewPromos': 'View Promotions',
    'hero.carouselSubtitle': 'Experience 4–5★ accommodation in Vinh Long',
    
    // Rooms
    'rooms.title': 'Rooms',
    'rooms.available': 'Available',
    'rooms.soldOut': 'Sold Out',
    'rooms.price': 'From',
    'rooms.perNight': '/night',
    'rooms.viewDetails': 'View Details',
    'rooms.explore': 'Explore Vinh Long',
    'rooms.quickSearch': 'Quick search for available rooms, good prices, full amenities',
    'rooms.filterDesc': 'Filter by date, star rating, amenities and number of guests to book rooms that meet your needs.',
    'rooms.filters': 'Filters',
    'rooms.clearAll': 'Clear All',
    'rooms.search': 'Search',
    'rooms.searchPlaceholder': 'Enter room name or description...',
    'rooms.area': 'Vinh Long Area',
    'rooms.allDistricts': 'All districts',
    'rooms.priceRange': 'Price Range (VND/night)',
    'rooms.all': 'All',
    'rooms.checkAvailability': 'Check Room Availability',
    'rooms.refresh': 'Refresh',
    'rooms.guestsCount': 'Number of Guests',
    'rooms.space': 'Space',
    'rooms.new': 'New',
    'rooms.freeCancel': 'Free Cancellation',
    'rooms.priceNote': 'Price for 1 night includes basic taxes/fees',
    'rooms.temporarilyClosed': 'Temporarily Closed',
    'rooms.nearDestinations': 'Rooms near tourist destinations',
    'rooms.noDestinations': 'No destinations available',
    'rooms.sort': 'Sort',
    'rooms.sortDefault': 'Default',
    'rooms.sortPriceAsc': 'Price: Low to High',
    'rooms.sortPriceDesc': 'Price: High to Low',
    'rooms.filterKeyword': 'Keyword',
    'rooms.filterArea': 'Area',
    'rooms.star': 'star',
    'rooms.filterPrice': 'Price',
    'rooms.filterStay': 'Stay',
    'rooms.filterGuests': 'Guests',
    'rooms.filterFacilities': 'Facilities',
    'rooms.filterDestinations': 'Destinations',
    'rooms.sortLowHigh': 'Price: Low → High',
    'rooms.sortHighLow': 'Price: High → Low',
    'rooms.noFiltersHint': 'Select filters to find rooms faster',
    'rooms.loading': 'Loading...',
    'rooms.searching': 'Searching for suitable rooms...',
    'rooms.noRating': 'No rating yet',
    'rooms.bookNow': 'Book Now',
    'rooms.details': 'Details',
    'rooms.prev': 'Previous',
    'rooms.next': 'Next',
    'rooms.showing': 'Showing',
    'rooms.ofTotal': 'of',
    'rooms.noRoomsFound': 'No suitable rooms found!',
    
    // Reviews
    'reviews.noRating': 'No rating yet',
    
    // Facilities
    'facilities.title': 'Facilities',
    'facilities.description': 'Discover modern facilities',
    'facilities.subtitle': 'AMENITIES & SERVICES',
    'facilities.intro': 'Vinh Long Hotel offers a modern and premium amenities system, meeting all your accommodation needs. <br>From high-speed Wi-Fi, air conditioning, television and water heaters, to minibars, kettles, work desks, wardrobes, full-length mirrors or irons – all are carefully equipped to provide absolute comfort. <br>You can relax at a professional spa, enjoy a spacious balcony, or immerse yourself in a luxurious private bathtub. <br>Vinh Long Hotel is proud to offer a complete, convenient and classy accommodation experience, helping you feel the difference in every moment of rest.',
    
    // Destinations
    'destinations.title': 'Destinations & Specialties',
    'destinations.description': 'Discover the beauty of Vinh Long',
    'destinations.pageTitle': 'Vinh Long Destinations',
    'destinations.subtitle': 'DISCOVER VINH LONG',
    'destinations.heading': 'VINH LONG TOURIST DESTINATIONS',
    'destinations.intro': 'Vinh Long is proud to have many attractive tourist destinations, from ancient temples, green islands, to ecological tourist areas and bustling floating markets. Discover the unique cultural and natural beauty of the Mekong Delta region, and find the nearest accommodation for a complete experience.',
    'destinations.searchPlaceholder': 'Search destinations, landmarks, locations...',
    'destinations.searchButton': 'Search',
    'destinations.searchSuggestions': 'Search suggestions',
    'destinations.searchHistory': 'Search history',
    'destinations.sortBy': 'Sort by:',
    'destinations.sortRatingDesc': 'Highest rating',
    'destinations.sortRatingAsc': 'Lowest rating',
    'destinations.sortNameAsc': 'Name A-Z',
    'destinations.sortNameDesc': 'Name Z-A',
    'destinations.sortReviewsDesc': 'Most reviews',
    'destinations.foundResults': 'Found',
    'destinations.destinations': 'destinations',
    'destinations.all': 'All',
    'destinations.categoryTemple': 'Temples, Communal Houses',
    'destinations.categoryNature': 'Nature',
    'destinations.categoryMarket': 'Floating Markets',
    'destinations.categoryCulture': 'Culture',
    'destinations.categoryOther': 'Other',
    'destinations.viewDetails': 'View details',
    'destinations.images': 'images',
    'destinations.reviews': 'reviews',
    'destinations.noResults': 'No destinations found',
    'destinations.noResultsDesc': 'Please try again with different filters.',
    'destinations.specialtiesSubtitle': 'LOCAL SPECIALTIES',
    'destinations.specialtiesHeading': 'VINH LONG SPECIALTIES',
    'destinations.specialtiesIntro': 'Discover the unique dishes, fruits and souvenirs of Vinh Long',
    'destinations.specialtyCategoryFood': 'Food',
    'destinations.specialtyCategoryFruit': 'Fruits',
    'destinations.specialtyCategoryDrink': 'Beverages',
    'destinations.specialtyCategorySouvenir': 'Souvenirs',
    'destinations.specialtyCategoryDefault': 'Specialties',
    'destinations.noSpecialties': 'No specialty information available',
    'destinations.noSpecialtiesDesc': 'Specialty information will be updated soon.',
    'destinations.loading': 'Loading...',
    'destinations.searching': 'Searching...',
    'specialtyDetails.home': 'Home',
    'specialtyDetails.destinations': 'Destinations',
    'specialtyDetails.price': 'Price',
    'specialtyDetails.bestSeason': 'Best Season',
    'specialtyDetails.location': 'Location',
    'specialtyDetails.rating': 'Rating',
    'specialtyDetails.reviews': 'reviews',
    'specialtyDetails.viewOnMap': 'View on Map',
    'specialtyDetails.getDirections': 'Get Directions',
    'specialtyDetails.buyLocations': 'Buy Locations',
    'specialtyDetails.contact': 'Contact',
    'specialtyDetails.address': 'Address',
    'specialtyDetails.phone': 'Phone',
    'specialtyDetails.website': 'Website',
    'specialtyDetails.giftSuggestion': 'Gift Suggestion',
    'specialtyDetails.openingHours': 'Opening Hours',
    'destinations.clearHistoryConfirm': 'Are you sure you want to clear search history?',
    'destinations.noSuggestions': 'No suggestions found',
    'destinations.caiBeFloatingMarket': 'Cai Be Floating Market',
    'destinations.tienChauTemple': 'Tien Chau Temple',
    'destinations.anBinhIsland': 'An Binh Island',
    'destinations.binhHoaPhuoc': 'Binh Hoa Phuoc Tourist Area',
    'destinations.tramChimEco': 'Tram Chim Ecological Tourist Area',
    'destinations.longHoVillage': 'Long Ho Weaving Village',
    'destinations.caiMonOrchard': 'Cai Mon Fruit Garden',
    'destinations.longThanhTemple': 'Long Thanh Temple',
    
    // Destination Details
    'destinationDetails.pageTitle': 'Destination Details',
    'destinationDetails.home': 'Home',
    'destinationDetails.destinations': 'Destinations',
    'destinationDetails.viewAllImages': 'View All Images',
    'destinationDetails.address': 'Address',
    'destinationDetails.coordinates': 'Coordinates',
    'destinationDetails.viewNearbyRooms': 'View Nearby Rooms',
    'destinationDetails.share': 'Share',
    'destinationDetails.facebook': 'Facebook',
    'destinationDetails.print': 'Print',
    'destinationDetails.backToList': 'Back to List',
    'destinationDetails.introduction': 'Introduction',
    'destinationDetails.summary': 'Summary',
    'destinationDetails.map': 'Map',
    'destinationDetails.viewLargeMap': 'View Large Map',
    'destinationDetails.nearbyRooms': 'Nearby Rooms',
    'destinationDetails.noNearbyRooms': 'No rooms near this destination yet.',
    'destinationDetails.kmAway': 'Away',
    'destinationDetails.perNight': '/night',
    'destinationDetails.viewRoom': 'View Room',
    'destinationDetails.similarDestinations': 'Similar Destinations',
    'destinationDetails.viewDetails': 'View Details',
    'destinationDetails.destinationImages': 'Destination Images',
    'destinationDetails.allImages': 'All Images',
    'destinationDetails.image': 'Image',
    'destinationDetails.reviews': 'reviews',
    
    // About
    'about.pageTitle': 'About Us',
    'about.subtitle': 'INTRODUCTION',
    'about.heading': 'ABOUT US',
    'about.studentInfo': 'K22 Students - Tra Vinh University - Faculty of Information Technology',
    'about.introTitle': 'Introduction',
    'about.intro1': 'We are a group of K22 students from Tra Vinh University, Faculty of Information Technology, young people full of enthusiasm and determination to deliver quality, creative and useful software products. Each member has their own strengths, but we share a common goal: to learn, develop and create real value through technology.',
    'about.intro2': 'With a sense of responsibility, seriousness in learning and passion for programming, the group always strives to improve ourselves every day and deliver creative, optimized and user-friendly products.',
    'about.intro3': 'We believe that:',
    'about.introQuote': 'Technology is a tool – people are the core value.',
    'about.statRooms': '100+ ROOMS',
    'about.statCustomers': '200+ CUSTOMERS',
    'about.statReviews': '150+ REVIEWS',
    'about.statStaff': '50+ STAFF',
    'about.teamTitle': 'VinhLongHotel Admin',
    'about.logoAlt': 'Tra Vinh University Logo',
    'about.siteAbout': '',
    
    // Testimonials
    'testimonials.title': 'What Our Guests Say',
    'testimonials.subtitle': 'Reviews from real guests',
    
    // Footer
    'footer.newsletter.title': 'Stay updated with latest offers & promotions',
    'footer.newsletter.description': 'Enter your email to receive the latest offers',
    'footer.newsletter.placeholder': 'Enter your email',
    'footer.newsletter.submit': 'Subscribe',
    'footer.newsletter.sending': 'Sending...',
    'footer.app.title': 'Your dream trip in your hands',
    'footer.app.description': 'Download the app and get offers',
    'footer.trust.security': 'Security',
    'footer.trust.support': '24/7 Support',
    'footer.trust.price': 'Best Price',
    'footer.payment.title': 'Payment Partners',
    
    // Language
    'language.toggle': 'Change language',
    'language.vi': 'Vietnamese',
    'language.en': 'English',
    
    // Contact
    'contact.title': 'Contact',
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    
    // Booking
    'booking.checkIn': 'Check In',
    'booking.checkOut': 'Check Out',
    'booking.guests': 'Guests',
    'booking.search': 'Search',
    'confirmBooking.room': 'Room',
    'confirmBooking.available': 'Available',
    'confirmBooking.rooms': 'rooms',
    'confirmBooking.adults': 'adults',
    'confirmBooking.children': 'children',
    'confirmBooking.freeWifi': 'Free WiFi',
    'confirmBooking.view': 'View',
    'confirmBooking.amenities': 'Amenities',
    'confirmBooking.map': 'Map',
    'confirmBooking.priceFrom': 'Price/room/night from',
    'confirmBooking.originalPrice': 'Original price',
    'confirmBooking.bookNow': 'Book Now',
    'confirmBooking.step1': 'Select Dates',
    'confirmBooking.step1Desc': 'Check availability',
    'confirmBooking.step2': 'Guest Information',
    'confirmBooking.step2Desc': 'Contact & requests',
    'confirmBooking.step3': 'Payment',
    'confirmBooking.step3Desc': 'Confirm QR',
    'confirmBooking.hotelMap': 'Hotel Map',
    'confirmBooking.allImages': 'All Images',
    'confirmBooking.images': 'images',
    'confirmBooking.viewAllImages': 'View All Images',
    'confirmBooking.overview': 'Room Overview',
    'confirmBooking.capacity': 'Capacity',
    'confirmBooking.area': 'Area',
    'confirmBooking.status': 'Status',
    'confirmBooking.mainFacilities': 'Main Facilities',
    'confirmBooking.fullAC': 'Full Air Conditioning',
    'confirmBooking.optionalBreakfast': 'Optional Breakfast',
    'confirmBooking.readMore': 'Read More',
    'confirmBooking.readLess': 'Show Less',
    'confirmBooking.reception24': '24/7 Reception',
    'confirmBooking.nearby': 'Nearby',
    'confirmBooking.nightMarket': 'Night Market / Central Market',
    'confirmBooking.cathedral': 'Cathedral',
    'confirmBooking.station': 'Central Station',
    'confirmBooking.supermarket': 'Supermarket & Convenience',
    'confirmBooking.reviewsFromGuests': 'Reviews from Guests',
    'confirmBooking.step2And3': 'Step 2 & 3',
    'confirmBooking.bookingDetails': 'Booking Details',
    'confirmBooking.discountApplied': 'Discount Applied',
    'confirmBooking.fullName': 'Full Name',
    'confirmBooking.phone': 'Phone Number',
    'confirmBooking.address': 'Address',
    'confirmBooking.checkInDate': 'Check-in Date',
    'confirmBooking.checkOutDate': 'Check-out Date',
    'confirmBooking.promoCode': 'Promo Code',
    'confirmBooking.enterPromoCode': 'Enter promo code',
    'confirmBooking.apply': 'Apply',
    'confirmBooking.selectSavedCode': 'Select Saved Code',
    'confirmBooking.savedFromHome': 'Codes saved from homepage (Save button in promo list).',
    'confirmBooking.specialRequest': 'Special Request (Optional)',
    'confirmBooking.specialRequestPlaceholder': 'E.g.: High floor room, river view...',
    'confirmBooking.checkAvailability': 'Check availability & calculate fees automatically after selecting dates.',
    'confirmBooking.upcomingBookings': 'Upcoming Booking Status',
    'confirmBooking.noBookings': 'No bookings scheduled. You can choose suitable dates.',
    'confirmBooking.pending': 'pending confirmation',
    'confirmBooking.booked': 'booked',
    'confirmBooking.roomPrice': 'Room Price',
    'confirmBooking.loyaltyDiscount': 'Member Discount',
    'confirmBooking.tax': 'Tax (8%)',
    'confirmBooking.serviceFee': 'Service Fee (2%)',
    'confirmBooking.discount': 'Discount',
    'confirmBooking.total': 'Total Payment',
    'confirmBooking.scanQR': 'Scan code with banking app/MoMo/ZaloPay.',
    'confirmBooking.amount': 'Amount',
    'confirmBooking.selectDatesAndConfirm': 'Select dates and confirm QR to unlock booking button.',
    'confirmBooking.paymentInfo': 'Select check-in/check-out dates, then double-tap the QR code to unlock payment button.',
    'confirmBooking.paymentButtonHint': 'Payment button will unlock when: valid dates selected, room available, and QR confirmed.',
    'confirmBooking.payNow': 'Pay Now',
    'confirmBooking.doubleTapQR': 'Double tap to confirm',
    'confirmBooking.copied': '✓ Copied',
    'confirmBooking.copyInfo': 'Copy Information',
    'confirmBooking.copyPaymentInfo': 'Payment information copied',
    'confirmBooking.cannotCopy': 'Cannot copy',
    'confirmBooking.noReviews': 'No reviews yet!',
    'confirmBooking.adminReply': 'Reply from Hotel Owner',
    'confirmBooking.helpful': 'Mark as helpful',
    'confirmBooking.thankYouReview': 'Thank you for leaving a review!',
    'confirmBooking.noSavedPromos': 'No saved codes',
    'confirmBooking.maxDiscount': 'max',
    'confirmBooking.minOrder': 'Minimum order',
    'confirmBooking.noMinRequired': 'No minimum required',
    'confirmBooking.savedCode': 'Saved code',
    
    // Bookings
    'bookings.pageTitle': 'Booking History',
    'bookings.home': 'Home',
    'bookings.bookingHistory': 'Booking History',
    'bookings.noBookings': 'No bookings yet',
    'bookings.noBookingsDesc': 'You have no booking history. Book a room now to experience our services!',
    'bookings.viewRooms': 'View Available Rooms',
    'bookings.checkIn': 'Check-in',
    'bookings.checkOut': 'Check-out',
    'bookings.nights': 'Nights',
    'bookings.totalAmount': 'Total Amount',
    'bookings.paymentMethod': 'Payment Method',
    'bookings.orderId': 'Order ID',
    'bookings.bookingDate': 'Booking Date',
    'bookings.address': 'Address',
    'bookings.roomNumber': 'Room Number',
    'bookings.statusBooked': 'Booked',
    'bookings.statusCancelled': 'Cancelled',
    'bookings.statusPending': 'Pending',
    'bookings.statusProcessing': 'Processing',
    'bookings.statusCancelledBadge': 'Cancelled',
    'bookings.paymentNotPaid': 'Not Paid',
    'bookings.paymentQR': 'QR Code / VietQR',
    'bookings.paymentMoMo': 'MoMo',
    'bookings.paymentZaloPay': 'ZaloPay',
    'bookings.paymentBank': 'Bank Transfer',
    'bookings.paymentCard': 'Credit/Debit Card',
    'bookings.paymentProcessing': 'Processing',
    'bookings.requirement': 'Requirement',
    'bookings.promoCode': 'Code',
    'bookings.refunding': 'Refunding',
    'bookings.refunded': 'Refunded',
    'bookings.yourReview': 'Your Review',
    'bookings.adminReply': 'Admin Reply',
    'bookings.review': 'Review',
    'bookings.cancel': 'Cancel Booking',
    'bookings.reviewAndComment': 'Review & Comment',
    'bookings.rating': 'Rating',
    'bookings.comment': 'Comment',
    'bookings.reviewImages': 'Review Images (max 5 images, 5MB each)',
    'bookings.acceptFormats': 'Accepted: JPG, PNG, WEBP',
    'bookings.selectRating': '-- Select Rating --',
    'bookings.rating5': '⭐ 5 - Excellent',
    'bookings.rating4': '⭐ 4 - Good',
    'bookings.rating3': '⭐ 3 - Average',
    'bookings.rating2': '⭐ 2 - Poor',
    'bookings.rating1': '⭐ 1 - Terrible',
    'bookings.reviewPlaceholder': 'Share your experience about this room...',
    'bookings.cancelBtn': 'Cancel',
    'bookings.submitReview': 'Submit Review',
    'bookings.perNight': '/ night',
    'bookings.nightsUnit': 'nights',
    
    // Profile
    'profile.pageTitle': 'Profile',
    'profile.home': 'Home',
    'profile.profile': 'Profile',
    'profile.myInfo': 'My Information',
    'profile.basicInfo': 'Basic Information',
    'profile.name': 'Name',
    'profile.email': 'Email',
    'profile.changeEmail': 'Change Email',
    'profile.password': 'Password',
    'profile.forgotPassword': 'Forgot Password?',
    'profile.forgotPasswordDesc': 'Click to receive OTP code to reset password',
    'profile.phone': 'Phone Number',
    'profile.dob': 'Date of Birth',
    'profile.idNumber': 'ID Number',
    'profile.gender': 'Gender',
    'profile.selectGender': '-- Select Gender --',
    'profile.male': 'Male',
    'profile.female': 'Female',
    'profile.address': 'Address',
    'profile.saveChanges': 'Save Changes',
    'profile.avatar': 'Avatar',
    'profile.selectNewImage': 'Select New Image',
    'profile.imageSupport': 'Supported: JPG, PNG, WEBP',
    'profile.changePassword': 'Change Password',
    'profile.oldPassword': 'Old Password',
    'profile.newPassword': 'New Password',
    'profile.confirmPassword': 'Confirm New Password',
    'profile.enterCurrentPassword': 'Enter current password',
    'profile.enterNewPassword': 'Enter new password',
    'profile.reEnterNewPassword': 'Re-enter new password',
    'profile.currentPasswordDesc': 'Please enter your current password to verify',
    'profile.minPasswordLength': 'Minimum 6 characters',
    'profile.passwordMatch': 'Must match new password',
    'profile.cancel': 'Cancel',
    'profile.favorites': 'Favorites',
    'profile.noFavorites': 'No favorite rooms yet',
    'profile.addToFavorites': 'Add to Favorites',
    'profile.list': 'List',
    'profile.details': 'Details',
    'profile.bookNow': 'Book now',
    'profile.adults': 'adults',
    'profile.children': 'children',
    'profile.night': 'night',
    'profile.removeFavorite': 'Remove from favorites',
    'profile.pleaseEnterNewEmail': 'Please enter new email!',
    'profile.invalidEmail': 'Invalid email!',
    'profile.newEmailMustDifferent': 'New email must be different from current email!',
    'profile.otpSent': 'Verification code has been sent to your new email!',
    'profile.emailAlreadyUsed': 'This email is already in use!',
    'profile.sessionExpired': 'Session expired. Please log in again!',
    'profile.userNotFound': 'User information not found!',
    'profile.otpSendFailed': 'Unable to send verification code. Please check email configuration or try again later!',
    'profile.emailChangedSuccess': 'Email changed successfully!',
    'profile.otpExpired': 'Verification code has expired. Please resend code!',
    'profile.updateSuccess': 'Update successful!',
    'profile.updateFailed': 'Update failed!',
    'profile.avatarUpdateSuccess': 'Avatar updated successfully!',
    'profile.pleaseFillAllFields': 'Please fill in all fields!',
    'profile.phoneAlreadyRegistered': 'This phone number is already registered!',
    'profile.loginToUseFavorites': 'Please log in to use favorites',
    'profile.favoriteUpdateError': 'Error updating favorites',
    'profile.sending': 'Sending...',
    'profile.errorOccurred': 'An error occurred',
    
    // Payment History
    'paymentHistory.pageTitle': 'Payment History',
    'paymentHistory.home': 'Home',
    'paymentHistory.paymentHistory': 'Payment History',
    'paymentHistory.totalPaid': 'Total Paid',
    'paymentHistory.totalTransactions': 'Total Transactions',
    'paymentHistory.noPayments': 'No Payment History',
    'paymentHistory.noPaymentsDesc': 'You have no payment transactions yet. Book a room and make a payment to see your history here!',
    'paymentHistory.orderId': 'Order ID',
    'paymentHistory.paymentDate': 'Payment Date',
    'paymentHistory.status': 'Status',
    'paymentHistory.amount': 'Amount',
    'paymentHistory.roomName': 'Room Name',
    'paymentHistory.checkIn': 'Check-in',
    'paymentHistory.checkOut': 'Check-out',
    'paymentHistory.statusSuccess': 'Success',
    'paymentHistory.statusPending': 'Pending',
    'paymentHistory.statusFailed': 'Failed',
    'paymentHistory.viewDetails': 'View Details',
    'paymentHistory.transactionId': 'Transaction ID',
    'paymentHistory.nights': 'Nights',
    'paymentHistory.pricePerNight': 'Price/Night',
    'paymentHistory.booking': 'Booking',
    'paymentHistory.nightsUnit': 'nights',
    
    // Messages
    'messages.pageTitle': 'Messages',
    'messages.messages': 'Messages',
    'messages.admin': 'Administrator',
    'messages.enterMessage': 'Enter message...',
    'messages.send': 'Send',
    'messages.noMessages': 'No messages yet. Start a conversation!',
    'messages.autoMessage': 'Auto message',
    'messages.sendError': 'An error occurred while sending message',
    'messages.conversations': 'Conversations',
    'messages.selectConversation': 'Select a conversation to start',
    
    // Reviews
    'reviews.title': 'Reviews',
    'reviews.write': 'Write Review',
    'reviews.rating': 'Rating',
    'reviews.comment': 'Comment',
    
    // Hero Section
    'hero.experience': 'Luxury experience in the heart of Vinh Long',
    'hero.title': 'Luxury resort hotel at attractive prices',
    'hero.description': 'Choose 4-5★ standard rooms, QR offers, 24/7 support.',
    'hero.exploreRooms': 'Explore Rooms',
    'hero.viewPromos': 'View Offers',
    
    // Search Box
    'search.location': 'Location',
    'search.checkIn': 'Check In',
    'search.checkOut': 'Check Out',
    'search.guests': 'Adults & Children',
    'search.stars': 'Stars',
    'search.search': 'Search',
    'search.selectLocation': 'Select location',
    'search.selectGuests': 'Select guests',
    'search.selectStars': 'Select stars',
    'search.area': 'Vinh Long Area',
    'search.selectArea': 'All areas',
    'search.adults': 'Adults',
    'search.children': 'Children',
    'search.adultsDesc': 'Ages 13 and above',
    'search.childrenDesc': 'Under 12 years old',
    'search.clear': 'Clear',
    'search.apply': 'Apply',
    'search.selectDatesHint': 'Please select both check-in and check-out dates',
    'search.selectGuestsHint': 'Please select at least 1 adult',
    
    // Sections
    'section.rooms': 'Room List',
    'section.roomsDesc': 'Choose a room that suits your needs',
    'section.facilities': 'Featured Facilities',
    'section.destinations': 'Destinations & Specialties',
    'section.testimonials': 'What Our Guests Say',
    'section.testimonialsDesc': 'Reviews from real guests',
    'section.whyChoose': 'Why book with Vinh Long Hotel?',
    'section.stats': 'Over 10,000 bookings, over 5,000 reviews',
    'section.rating': 'Rating',
    'section.satisfied': 'Satisfied',
    
    // Why Choose Cards
    'why.meetNeeds': 'Meet all your needs',
    'why.meetNeedsDesc': 'From rooms, facilities, to attractions, you can trust our complete service and travel guide.',
    'why.flexibleBooking': 'Flexible booking options',
    'why.flexibleBookingDesc': 'Plans changed unexpectedly? Don\'t worry! Easy to change schedule or refund.',
    'why.safePayment': 'Safe and convenient payment',
    'why.safePaymentDesc': 'Enjoy many safe payment methods, in the most convenient currency for you.',
    'why.quality': '5-star service quality',
    'why.qualityDesc': 'Comfortable rooms, professional service, meeting international standards and highly rated by customers.',
    
    // Room Cards
    'room.viewDetails': 'View Details',
    'room.perNight': '/night',
    'room.popular': 'Popular',
    'room.discount': 'Discount',
    
    // Promos
    'promo.title': 'Attractive Promo Codes',
    'promo.offers': 'Offers',
    'promo.onlineOnly': 'Only applies when booking online',
    'promo.copyAll': 'Copy All',
    'promo.copyAllTitle': 'Copy all promo codes',
    'promo.codeLabel': 'Promo Code',
    'promo.copy': 'Copy',
    'promo.save': 'Save',
    'promo.saveTitle': 'Save this code',
    'promo.expires': 'Expires',
    'promo.unlimited': 'Unlimited',
    'promo.expiresIn2Days': 'Expires in 2 days',
    'promo.expiresIn': 'Expires in',
    'promo.expired': 'Expired',
    'promo.runningOut': 'Running out',
    'promo.limited': 'Limited',
    'promo.bankOffer': 'Bank Offer',
    'promo.qrPayment': 'QR Payment',
    'promo.hotDestination': 'Hot Destination',
    
    // Promo labels mapping for saved codes
    'promo.label.Thanh toán QR': 'QR Payment',
    'promo.label.Điểm đến hot': 'Hot Destination',
    'promo.label.Ưu đãi ngân hàng': 'Bank Offer',
    'promo.label.Sắp hết mã': 'Running out',
    'promo.label.Hết hạn sau 2 ngày': 'Expires in 2 days',
    'promo.label.Có hạn': 'Limited',
    
    // Reviews
    'reviews.feelings': 'Feelings',
    'reviews.fromGuests': 'Reviews from Guests',
    'reviews.total': 'Total Reviews',
    'reviews.average': 'Average Rating',
    'reviews.satisfied': 'Satisfied Customers',
    'reviews.viewAll': 'View All Reviews',
    'reviews.updating': 'Updating reviews from customers.',
    'reviews.guest': 'Guest',
    'reviews.noReview': 'No detailed review yet.',
    'reviews.verified': 'Verified Customer',
    'reviews.today': 'Today',
    'reviews.yesterday': 'Yesterday',
    'reviews.daysAgo': 'days ago',
    'reviews.weeksAgo': 'weeks ago',
    'reviews.monthsAgo': 'months ago',
    'reviews.yearsAgo': 'years ago',
    
    // Room
    'room.viewAll': 'View All Rooms',
    'room.viewRoom': 'View Room',
    'room.discountPercent': 'Discount',
    'room.adults': 'adults',
    'room.children': 'children',
    'room.updating': 'Updating',
    'room.updatingFacilities': 'Updating facilities',
    'room.bookNow': 'Book Now',
    'room.soldOut': 'Sold Out',
    'room.details': 'Details',
    'room.features': 'Featured Features',
    'room.remaining': 'Remaining',
    'room.rooms': 'rooms',
    'room.reviewFrom': 'Review from room',
    'room.space': 'Space',
    'room.facilities': 'Facilities',
    
    // Features (Room Amenities)
    'features.bedroom': 'Bedroom',
    'features.balcony': 'Balcony',
    'features.kitchen': 'Kitchen',
    'features.sofa': 'Sofa',
    'features.bathroom': 'Bathroom',
    'features.livingRoom': 'Living Room',
    'features.refrigerator': 'Refrigerator',
    'features.airConditioner': 'Air Conditioner',
    'features.tv': 'TV',
    'features.wifi': 'WiFi',
    
    // Facilities
    'facilities.viewMore': 'View More Facilities',
    'facilities.wifi': 'Wi-Fi',
    'facilities.tv': 'Television',
    'facilities.spa': 'Spa',
    'facilities.heater': 'Heater',
    'facilities.heaterDesc': 'The heating system helps guests enjoy a warm space in the cold season.',
    'facilities.airConditioner': 'Air Conditioner',
    'facilities.waterHeater': 'Water Heater',
    'facilities.hairDryer': 'Hair Dryer',
    'facilities.personalHygiene': 'Personal Hygiene Items',
    'facilities.minibar': 'Minibar',
    'facilities.kettle': 'Kettle',
    'facilities.workspace': 'Workspace',
    'facilities.wardrobe': 'Wardrobe',
    'facilities.slippers': 'Slippers',
    'facilities.fullMirror': 'Full-length Mirror',
    'facilities.iron': 'Iron',
    'facilities.service24': '24/24 Hour Service',
    'facilities.service24Desc': '24/24 reception service, always ready to support all customer needs.',
    'facilities.airportShuttle': 'Airport Shuttle',
    'facilities.airportShuttleDesc': 'Fast, convenient, and safe airport shuttle service.',
    'facilities.swimmingPool': 'Swimming Pool',
    'facilities.swimmingPoolDesc': 'Outdoor swimming pool, clear blue water, suitable for relaxing or swimming.',
    'facilities.golfCourse': 'Golf Course',
    'facilities.golfCourseDesc': 'Golf course near the hotel, a high-class entertainment area.',
    'facilities.bar': 'Bar Counter',
    'facilities.barDesc': 'Luxurious bar with a variety of drinks, serving guests for evening relaxation.',
    'facilities.freeWifi': 'Free WiFi',
    'facilities.parking': 'Parking',
    'facilities.restaurant': 'Restaurant',
    'facilities.gym': 'Gym',
    'facilities.spa': 'Spa',
    'facilities.laundry': 'Laundry Service',
    
    // Contact
    'contact.support247': '24/7 Support',
    'contact.readyToHelp': 'We are always ready to support you anytime',
    'contact.hotelLocation': 'Hotel Location',
    'contact.viewLargeMap': 'View Large Map',
    'contact.address': 'Address',
    'contact.directions': 'Directions',
    'contact.guide': 'Guide',
    'contact.guide1': 'Easy to find from the city center',
    'contact.guide2': 'Free parking available',
    'contact.guide3': 'Close to famous tourist attractions',
    'contact.nearby': 'Nearby Attractions',
    'contact.transportation': 'Transportation',
    'contact.transport1': 'Parking available',
    'contact.transport2': 'Easy to call a taxi',
    'contact.transport3': 'Can walk from the center',
    'contact.quickConnect': 'Quick Connect',
    'contact.hotline': 'Hotline',
    'contact.workingHours': 'Working Hours',
    'contact.hours247': 'Monday - Sunday: 24/7',
    'contact.supportAnytime': 'Customer support anytime',
    'contact.followUs': 'Follow Us',
    'contact.sendMessage': 'Send Message',
    'contact.responseTime': 'Response within 1 hour',
    'contact.leaveMessage': 'Leave a Message',
    'contact.response24h': 'We will respond within 24 hours',
    'contact.nameLabel': 'Name',
    'contact.emailLabel': 'Email',
    'contact.subjectLabel': 'Subject',
    'contact.messageLabel': 'Message',
    'contact.namePlaceholder': 'Enter your name',
    'contact.subjectPlaceholder': 'Message subject',
    'contact.messagePlaceholder': 'Enter your message content...',
    'contact.minChars': 'Minimum 10 characters',
    'contact.copyPhone': 'Copy phone number',
    'contact.copyEmail': 'Copy email',
    'contact.copied': 'Copied!',
    'contact.sending': 'Sending...',
    'contact.viewMap': 'View location on map',
    'contact.nightMarket': 'Night Market',
    'contact.cathedral': 'Cathedral',
    'contact.station': 'Central Station',
    'contact.supermarket': 'Supermarket',
    'contact.km': 'km',
    'contact.m': 'm',
    
    // Room Details
    'roomDetails.pageTitle': 'Room Details',
    'roomDetails.home': 'Home',
    'roomDetails.roomList': 'Room List',
    'roomDetails.adults': 'adults',
    'roomDetails.children': 'children',
    'roomDetails.postedBy': 'Posted by',
    'roomDetails.admin': 'System Administrator',
    'roomDetails.owner': 'Hotel Owner',
    'roomDetails.message': 'Message',
    'roomDetails.priceFrom': 'Price from',
    'roomDetails.originalPrice': 'Original price',
    'roomDetails.discount': 'Discount',
    'roomDetails.perNight': '/ night',
    'roomDetails.description': 'Room Description',
    'roomDetails.readMore': 'Read More',
    'roomDetails.readLess': 'Show Less',
    'roomDetails.nearbyDestinations': 'Nearby Destinations',
    'roomDetails.viewDetails': 'View Details',
    'roomDetails.viewAllDestinations': 'View All Destinations',
    'roomDetails.noNearbyDestinations': 'No nearby destination information available for this room.',
    'roomDetails.exploreDestinations': 'Explore Vinh Long Destinations',
    'roomDetails.relatedRooms': 'Related Rooms',
    'roomDetails.viewAllRooms': 'View All Rooms',
    'roomDetails.noRelatedRooms': 'No related rooms available.',
    'roomDetails.exploreRooms': 'Explore All Rooms',
    'roomDetails.customerExperience': 'Customer Experience',
    'roomDetails.noReviews': 'No reviews yet!',
    'roomDetails.adminReply': 'Reply from Hotel Owner',
    'roomDetails.helpful': 'Mark as helpful',
    'roomDetails.priceSummary': 'Price Summary',
    'roomDetails.nights': 'nights',
    'roomDetails.roomPrice': 'Room Price',
    'roomDetails.tax': 'Tax (8%)',
    'roomDetails.serviceFee': 'Service Fee (2%)',
    'roomDetails.subtotal': 'Subtotal',
    'roomDetails.space': 'Space',
    'roomDetails.facilities': 'Facilities',
    'roomDetails.noInfo': 'No information available',
    'roomDetails.capacity': 'Capacity & Area',
    'roomDetails.bookNow': 'Book Now',
    'roomDetails.soldOut': 'Sold Out',
    'roomDetails.available': 'Available',
    'roomDetails.rooms': 'rooms',
    'roomDetails.location': 'Location',
    'roomDetails.viewLargeMap': 'View Large Map',
    'roomDetails.kmAway': 'Away',
    'roomDetails.km': 'km',
    
    // Footer
    'footer.exploreBook': 'Explore & book rooms Vinh Long',
    'footer.partner': 'Partner with',
    'footer.about': 'About Vinh Long Hotel',
    'footer.howToBook': 'How to Book',
    'footer.contactUs': 'Contact Us',
    'footer.products': 'Products',
    'footer.hotels': 'Hotels',
    'footer.flights': 'Flight Tickets',
    'footer.bus': 'Bus Tickets',
    'footer.cruises': 'Cruises',
    'footer.villas': 'Villas',
    'footer.apartments': 'Apartments',
    'footer.forOwners': 'For Hotel Owners',
    'footer.registerAccount': 'Register Account',
    'footer.ownerLogin': 'Management Login',
    'footer.manageHotel': 'Manage Your Hotel',
    'footer.contactSupport': 'Contact Support',
    'footer.others': 'Others',
    'footer.affiliate': 'Vinh Long Hotel Affiliate',
    'footer.referFriends': 'Refer Friends',
    'footer.blog': 'Vinh Long Hotel Blog',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms & Conditions',
    'footer.press': 'Press Area',
    'footer.regulations': 'Operating Regulations',
    'footer.followUs': 'Follow Us',
    'footer.downloadApp': 'Download App',
  }
};

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
  module.exports = translations;
}

